/* Lexicon Artist — the word bank.
 *
 * Every entry: { w: word, pos: part of speech, def: definition, real: true|false, note: shown after the guess }
 *
 * REAL entries are genuine English words with genuine definitions.
 * FAKE entries are inventions — plausible shapes, plausible meanings, no dictionary.
 * To add words, just append to either array. The game picks 5 real + 5 fake per round.
 */

const REAL_WORDS = [
  { w: "borborygmus", pos: "noun", def: "the rumbling noise made by gas moving through the intestines", note: "Real. From Greek <em>borborygmos</em> — the word is basically the sound." , ex: "The lecture hall fell silent just in time for everyone to hear the <em>borborygmus</em> from the back row." , lvl: 3 },
  { w: "petrichor", pos: "noun", def: "the pleasant earthy smell that follows rain falling on dry ground", note: "Real. Coined in 1964 by two Australian scientists, from Greek <em>petra</em> (stone) + <em>ichor</em> (the fluid in the veins of the gods)." , ex: "She opened the window after the storm and breathed in the <em>petrichor</em> rising off the hot pavement." , lvl: 2 },
  { w: "defenestration", pos: "noun", def: "the act of throwing someone or something out of a window", note: "Real. The Defenestrations of Prague (1419 and 1618) helped touch off two wars." , ex: "The <em>defenestration</em> of two royal officials in Prague in 1618 helped start a thirty-year war." , lvl: 1 },
  { w: "absquatulate", pos: "verb", def: "to leave abruptly; to make off with something", note: "Real. Nineteenth-century American mock-Latin — the frontier press loved inventing words that sounded classical." , ex: "He <em>absquatulated</em> with the petty cash before anyone thought to count it." , lvl: 2 },
  { w: "gallimaufry", pos: "noun", def: "a confused jumble or medley of things", note: "Real. It started life as a stew made of whatever was left in the kitchen." , ex: "The exhibition was a <em>gallimaufry</em> of half-finished sketches, ships' logs and stuffed birds." , lvl: 3 },
  { w: "mumpsimus", pos: "noun", def: "a stubborn adherence to a habit or notion even after it is shown to be wrong", note: "Real. From a priest who kept misreading the Latin <em>sumpsimus</em> as <em>mumpsimus</em> and refused to be corrected." , ex: "Correcting his grammar was hopeless; the man was a <em>mumpsimus</em> about the split infinitive." , lvl: 3 },
  { w: "sesquipedalian", pos: "adjective", def: "(of a word) very long; given to using long words", note: "Real, and self-demonstrating. Literally 'a foot and a half long', from Horace." , ex: "Her <em>sesquipedalian</em> prose sent readers to the dictionary twice a paragraph." , lvl: 2 },
  { w: "tergiversate", pos: "verb", def: "to make conflicting or evasive statements; to switch loyalties", note: "Real. Latin <em>tergum</em> (back) + <em>versare</em> (to turn) — to turn your back." , ex: "The minister <em>tergiversated</em> for a week before admitting he had changed sides." , lvl: 2 },
  { w: "ultracrepidarian", pos: "noun", def: "a person who gives opinions on matters beyond their knowledge", note: "Real. From a cobbler who criticised a painting above the shoe line: <em>ne sutor ultra crepidam</em>." , ex: "Every comment section has its <em>ultracrepidarian</em>, explaining epidemiology to epidemiologists." , lvl: 3 },
  { w: "widdershins", pos: "adverb", def: "in a direction contrary to the sun's course; counterclockwise", note: "Real. Scots, and long thought to be unlucky." , ex: "Superstitious sailors never walked <em>widdershins</em> around the mast." , lvl: 2 },
  { w: "zugzwang", pos: "noun", def: "a position in which any move a player can make will worsen it", note: "Real — a chess term borrowed whole from German: 'compulsion to move'." , ex: "Two moves from the end he was in <em>zugzwang</em>: every legal move lost a piece." , lvl: 1 },
  { w: "quidnunc", pos: "noun", def: "an inquisitive, gossiping person; a busybody", note: "Real. From the Latin <em>quid nunc?</em> — 'what now?'" , ex: "The village <em>quidnunc</em> knew about the engagement before the couple did." , lvl: 2 },
  { w: "rebarbative", pos: "adjective", def: "unattractive and objectionable; repellent", note: "Real. From French — literally to stand beard-to-beard with someone." , ex: "His manner was so <em>rebarbative</em> that even the dog left the room." , lvl: 3 },
  { w: "snollygoster", pos: "noun", def: "a shrewd, unprincipled person, especially a politician", note: "Real. Nineteenth-century American, and overdue for a comeback." , ex: "The editorial called the new senator a <em>snollygoster</em> with a talent for the microphone." , lvl: 3 },
  { w: "velleity", pos: "noun", def: "a wish or inclination too slight to lead to any action", note: "Real. From Latin <em>velle</em>, to wish. The word for wanting to go to the gym." , ex: "Learning the cello remained a <em>velleity</em>; the instrument stayed in its case for years." , lvl: 3 },
  { w: "floccinaucinihilipilification", pos: "noun", def: "the act of estimating something as worthless", note: "Real, if barely used — it was assembled in the 18th century out of four Latin words all meaning 'trifle'." , ex: "His <em>floccinaucinihilipilification</em> of modern art was as tiresome as the word itself." , lvl: 3 },
  { w: "cachinnate", pos: "verb", def: "to laugh loudly or immoderately", note: "Real. Latin <em>cachinnare</em>, to guffaw." , ex: "The audience <em>cachinnated</em> so loudly that the actors had to wait to go on." , lvl: 3 },
  { w: "brontide", pos: "noun", def: "a low muffled rumbling like distant thunder", note: "Real. From Greek <em>bronte</em>, thunder — the same root as the dinosaur." , ex: "A low <em>brontide</em> rolled across the valley long before the first clouds appeared." , lvl: 3 },
  { w: "limerence", pos: "noun", def: "the state of being obsessively infatuated with another person", note: "Real. Coined by the psychologist Dorothy Tennov in the 1970s and now in wide use." , ex: "Six months of <em>limerence</em> ended the moment she heard him chew." , lvl: 2 },
  { w: "deipnosophist", pos: "noun", def: "a person skilled in table talk", note: "Real. From Athenaeus's third-century work <em>The Deipnosophists</em> — dinner guests who talk beautifully." , ex: "A born <em>deipnosophist</em>, he could keep eight strangers talking through four courses." , lvl: 3 },
  { w: "mondegreen", pos: "noun", def: "a misheard word or phrase, especially in a song lyric", note: "Real. Coined in 1954 from 'laid him on the green' misheard as 'Lady Mondegreen'." , ex: "'Sweet dreams are made of cheese' is the most cheerful <em>mondegreen</em> in pop music." , lvl: 3 },
  { w: "callipygian", pos: "adjective", def: "having shapely buttocks", note: "Real. Greek <em>kallos</em> (beauty) + <em>pyge</em>. There is a famous statue named for it." , ex: "The museum's <em>callipygian</em> statue drew more visitors than the entire Roman wing." , lvl: 3 },
  { w: "bibulous", pos: "adjective", def: "excessively fond of drinking alcohol; also, absorbent", note: "Real. Latin <em>bibere</em>, to drink — the same root as 'imbibe'." , ex: "After a <em>bibulous</em> evening at the club, he took the long way home." , lvl: 2 },
  { w: "jentacular", pos: "adjective", def: "relating to breakfast", note: "Real, if archaic. From Latin <em>jentaculum</em>, the first meal of the day." , ex: "He defended his <em>jentacular</em> habits: two eggs, black coffee, and no conversation." , lvl: 2 },
  { w: "kakistocracy", pos: "noun", def: "government by the worst or least qualified people", note: "Real. Greek <em>kakistos</em>, worst. In use since the 1600s." , ex: "The pamphlet argued that the republic had slid into outright <em>kakistocracy</em>." , lvl: 3 },
  { w: "matutinal", pos: "adjective", def: "of or occurring in the morning", note: "Real. The opposite number is 'vespertine', of the evening." , ex: "Her <em>matutinal</em> routine — swim, coffee, newspaper — did not vary in thirty years." , lvl: 2 },
  { w: "obnubilate", pos: "verb", def: "to darken, dim, or obscure", note: "Real. Latin <em>nubes</em>, cloud — literally to cloud over." , ex: "Smoke from the fires <em>obnubilated</em> the sun for three days." , lvl: 3 },
  { w: "pandiculation", pos: "noun", def: "the stretching and yawning that accompanies waking", note: "Real, and used in medicine. Cats are experts." , ex: "The cat's morning <em>pandiculation</em> took longer than breakfast." , lvl: 3 },
  { w: "quockerwodger", pos: "noun", def: "a wooden puppet on strings; hence a politician controlled by someone else", note: "Real Victorian slang. Yes, really." , ex: "The cartoonist drew the governor as a <em>quockerwodger</em>, strings running up to the lobbyists." , lvl: 3 },
  { w: "rodomontade", pos: "noun", def: "boastful or inflated talk", note: "Real. From Rodomonte, a swaggering braggart in Italian romance." , ex: "The speech was pure <em>rodomontade</em>: twenty minutes of promises and not one number." , lvl: 2 },
  { w: "tatterdemalion", pos: "noun", def: "a person in ragged clothing", note: "Real, first recorded in the early 1600s." , ex: "A <em>tatterdemalion</em> band of survivors reached the fort at dawn." , lvl: 2 },
  { w: "usufruct", pos: "noun", def: "the legal right to use and enjoy the profits of property belonging to another", note: "Real. Straight out of Roman law and still live in modern civil codes." , ex: "The will left her the <em>usufruct</em> of the orchard, though the land itself passed to her nephew." , lvl: 2 },
  { w: "yaffle", pos: "noun", def: "a green woodpecker", note: "Real British dialect, imitating the bird's laughing call." , ex: "A <em>yaffle</em> laughed somewhere in the beeches and then went quiet." , lvl: 2 },
  { w: "agelast", pos: "noun", def: "a person who never laughs", note: "Real. Greek <em>a-</em> (not) + <em>gelan</em> (to laugh)." , ex: "He was a complete <em>agelast</em> — twelve years of friendship, and nobody had seen him smile." , lvl: 3 },
  { w: "bloviate", pos: "verb", def: "to speak or write at length in a pompous, empty way", note: "Real American coinage, forever associated with President Warren G. Harding." , ex: "Given a microphone, he would <em>bloviate</em> about the deficit until the room emptied." , lvl: 3 },
  { w: "hebetude", pos: "noun", def: "dullness of mind; mental lethargy", note: "Real. Latin <em>hebes</em>, blunt." , ex: "August heat brought a general <em>hebetude</em> to the office; nothing was decided until September." , lvl: 3 },
  { w: "incunabula", pos: "noun", def: "books printed before 1501; by extension, the earliest stages of something", note: "Real. Latin for 'swaddling clothes' — the infancy of printing." , ex: "The library's <em>incunabula</em> are kept behind glass, in gloves-only conditions." , lvl: 2 },
  { w: "fuliginous", pos: "adjective", def: "sooty; of the colour of soot", note: "Real. Latin <em>fuligo</em>, soot." , ex: "A <em>fuliginous</em> haze hung over the ironworks even on still days." , lvl: 3 },
  { w: "crepuscular", pos: "adjective", def: "of or resembling twilight; (of animals) active at dawn and dusk", note: "Real. Deer, rabbits and mosquitoes are all crepuscular." , ex: "Deer are <em>crepuscular</em>, which is why they meet so many cars at dusk." , lvl: 2 },
  { w: "lachrymose", pos: "adjective", def: "tearful, or inclined to produce tears", note: "Real. Latin <em>lacrima</em>, tear." , ex: "Three glasses in, he turned <em>lachrymose</em> about a dog he had owned in 1994." , lvl: 1 },
  { w: "anserine", pos: "adjective", def: "of or resembling a goose; hence, silly", note: "Real. Latin <em>anser</em>, goose — the bird equivalent of 'bovine'." , ex: "She dismissed the whole plan with an <em>anserine</em> giggle and no argument at all." , lvl: 3 },
  { w: "scrimshaw", pos: "noun", def: "carved or engraved work in whalebone or ivory, made by sailors", note: "Real. A whaling-ship craft from the 1800s." , ex: "The captain's <em>scrimshaw</em> — a whale's tooth carved with a full-rigged ship — sold for thousands." , lvl: 1 },
  { w: "epizeuxis", pos: "noun", def: "the immediate repetition of a word for emphasis", note: "Real — a rhetorical figure. 'Never, never, never give up.'" , ex: "Churchill's 'never, never, never' is <em>epizeuxis</em> doing the work of a paragraph." , lvl: 3 },
  { w: "nyctalopia", pos: "noun", def: "night blindness; poor vision in low light", note: "Real, and a genuine medical diagnosis, often from vitamin A deficiency." , ex: "His <em>nyctalopia</em> made driving after sunset out of the question." , lvl: 3 },
  { w: "zoanthropy", pos: "noun", def: "the delusion that one has become an animal", note: "Real, an old psychiatric term. Lycanthropy is the wolf-specific version." , ex: "The old case notes described a patient with <em>zoanthropy</em> who was certain he was a wolf." , lvl: 3 },
  { w: "abecedarian", pos: "noun", def: "a person learning the alphabet; a beginner in any subject", note: "Real. Named for the first four letters — A, B, C, D." , ex: "At forty he was a cheerful <em>abecedarian</em> in Japanese, still proud of his hiragana." , lvl: 3 },
  { w: "aeolian", pos: "adjective", def: "produced or carried by the wind", note: "Real. From Aeolus, keeper of the winds. An aeolian harp is played by the breeze alone." , ex: "The <em>aeolian</em> ridges of the dune shifted a few feet every winter." , lvl: 2 },
  { w: "apotropaic", pos: "adjective", def: "intended to ward off evil", note: "Real. Horseshoes over doorways and gargoyles on churches are both apotropaic." , ex: "The blue beads above the doorway were <em>apotropaic</em>, hung there to turn away the evil eye." , lvl: 3 },
  { w: "autochthonous", pos: "adjective", def: "native to the place where it is found", note: "Real. Greek <em>autos</em> (self) + <em>chthon</em> (earth) — sprung from the ground itself." , ex: "The valley's <em>autochthonous</em> oaks predate every wall and road around them." , lvl: 2 },
  { w: "bezoar", pos: "noun", def: "a hard mass of undigested material found in the stomach", note: "Real. For centuries it was believed to be an antidote to every poison." , ex: "A Renaissance prince would pay a fortune for a <em>bezoar</em>, believing it neutralised any poison." , lvl: 1 },
  { w: "blatherskite", pos: "noun", def: "a person who talks at great length without making sense", note: "Real. Scots by birth, and popular in America since the Revolution." , ex: "The meeting was hijacked by a <em>blatherskite</em> from accounts with forty slides." , lvl: 1 },
  { w: "brumal", pos: "adjective", def: "belonging to or occurring in winter", note: "Real. From Latin <em>bruma</em>, the winter solstice." , ex: "The house takes on a <em>brumal</em> silence once the last visitors leave in November." , lvl: 3 },
  { w: "cacoethes", pos: "noun", def: "an irresistible urge to do something inadvisable", note: "Real. Greek for a bad habit. <em>Cacoethes scribendi</em> is the incurable itch to write." , ex: "She had a <em>cacoethes</em> for buying houseplants she had no light to keep alive." , lvl: 3 },
  { w: "caliginous", pos: "adjective", def: "misty, dim, obscure", note: "Real. From Latin <em>caligo</em>, mist." , ex: "The path vanished into a <em>caliginous</em> stretch of woodland." , lvl: 3 },
  { w: "chiaroscuro", pos: "noun", def: "the arrangement of light and shade in a picture", note: "Real. Italian for light-dark. Caravaggio built a career on it." , ex: "The portrait's <em>chiaroscuro</em> leaves half the sitter's face in darkness." , lvl: 1 },
  { w: "clerisy", pos: "noun", def: "the learned class taken as a whole", note: "Real. Coined by Samuel Taylor Coleridge, who felt England needed one." , ex: "He wrote for the <em>clerisy</em> and was baffled when the book sold twelve copies." , lvl: 3 },
  { w: "collywobbles", pos: "noun", def: "stomach pain, or a feeling of nervousness", note: "Real. Probably a playful mangling of <em>cholera morbus</em>." , ex: "Waiting in the wings gave her the <em>collywobbles</em> every single night." , lvl: 2 },
  { w: "concinnity", pos: "noun", def: "elegant harmony in the way parts are arranged", note: "Real. A favourite term of Cicero's admirers." , ex: "There is a <em>concinnity</em> to her sentences that survives translation." , lvl: 3 },
  { w: "crapulous", pos: "adjective", def: "suffering the effects of too much drink", note: "Real. From Latin <em>crapula</em>, intoxication." , ex: "He arrived <em>crapulous</em> and unshaven, an hour after the ceremony began." , lvl: 2 },
  { w: "desuetude", pos: "noun", def: "a state of disuse", note: "Real. Laws nobody bothers to enforce are said to fall into desuetude." , ex: "The duelling statutes fell into <em>desuetude</em> long before anyone repealed them." , lvl: 3 },
  { w: "dolorous", pos: "adjective", def: "feeling or expressing great sorrow", note: "Real. From Latin <em>dolor</em>, pain — the same root that gives us <em>condolences</em>.", ex: "A <em>dolorous</em> horn sounded twice from the far side of the lake." , lvl: 2 },
  { w: "logorrhea", pos: "noun", def: "excessive and often incoherent talkativeness", note: "Real, and a genuine clinical term. Greek <em>logos</em> (word) + <em>rhein</em> (to flow).", ex: "The witness's <em>logorrhea</em> filled ninety pages of transcript and settled nothing." , lvl: 2 },
  { w: "eldritch", pos: "adjective", def: "weird, eerie, unearthly", note: "Real. Scots, and the reason so much horror fiction sounds Scottish." , ex: "An <em>eldritch</em> light moved across the marsh, and nobody volunteered to investigate." , lvl: 1 },
  { w: "embrocation", pos: "noun", def: "a liquid rubbed into the body to relieve aches", note: "Real. Standard issue in every nineteenth-century medicine cabinet." , ex: "The trainer worked <em>embrocation</em> into the horse's shoulder before the race." , lvl: 2 },
  { w: "farrago", pos: "noun", def: "a confused mixture", note: "Real. Latin for mixed fodder fed to cattle." , ex: "The report was a <em>farrago</em> of rumour, guesswork and one genuine fact." , lvl: 1 },
  { w: "fissiparous", pos: "adjective", def: "inclined to split into factions", note: "Real. Biology got it first, for cells that reproduce by dividing." , ex: "The party proved <em>fissiparous</em>, splitting into three factions within a year." , lvl: 3 },
  { w: "flibbertigibbet", pos: "noun", def: "a frivolous, flighty person", note: "Real. It began as the name of a devil in <em>King Lear</em>." , ex: "Her aunt dismissed the new fiancée as a <em>flibbertigibbet</em> with no head for money." , lvl: 1 },
  { w: "frangible", pos: "adjective", def: "easily broken; fragile", note: "Real. Same root as 'fracture'." , ex: "The bones of a bird are <em>frangible</em>, built for lightness rather than strength." , lvl: 2 },
  { w: "gasconade", pos: "noun", def: "extravagant boasting", note: "Real. From Gascony, whose people had a reputation for exactly that." , ex: "His account of the hunt was mostly <em>gasconade</em>; the deer had escaped." , lvl: 2 },
  { w: "gormless", pos: "adjective", def: "lacking sense or initiative", note: "Real. From an old northern English word, <em>gaum</em>, meaning understanding." , ex: "He stood there <em>gormless</em>, holding a bouquet at the wrong address." , lvl: 1 },
  { w: "haruspex", pos: "noun", def: "a Roman priest who read omens in the entrails of sacrificed animals", note: "Real. A recognised public office, with training." , ex: "Before the battle, the <em>haruspex</em> examined the liver and pronounced the omens good." , lvl: 2 },
  { w: "hypnagogic", pos: "adjective", def: "of the drowsy state just before falling asleep", note: "Real. That sudden falling sensation is a hypnagogic jerk." , ex: "In that <em>hypnagogic</em> drift before sleep she often heard her name called." , lvl: 2 },
  { w: "imbroglio", pos: "noun", def: "a confused or embarrassing situation", note: "Real. Italian, from the same root as 'embroil'." , ex: "The entire <em>imbroglio</em> began with one misdirected email." , lvl: 1 },
  { w: "inglenook", pos: "noun", def: "a recess beside a large fireplace", note: "Real. 'Ingle' is an old word for the fire on a hearth." , ex: "They took the corner seats in the <em>inglenook</em>, closest to the fire." , lvl: 3 },
  { w: "interrobang", pos: "noun", def: "a punctuation mark combining a question mark and an exclamation point", note: "Real. Invented in 1962 by an advertising executive. It looks like this: &#8253;" , ex: "Nothing else punctuates 'you did what' quite like an <em>interrobang</em>." , lvl: 2 },
  { w: "kerfuffle", pos: "noun", def: "a commotion or fuss", note: "Real. Scots, and still in daily use." , ex: "There was a brief <em>kerfuffle</em> at the door over an unpaid bar tab." , lvl: 1 },
  { w: "lacuna", pos: "noun", def: "a gap, especially a missing portion of a text", note: "Real. Latin for a pit or pool." , ex: "The manuscript has a <em>lacuna</em> where three lines were lost to damp." , lvl: 2 },
  { w: "lambent", pos: "adjective", def: "glowing or flickering with a soft radiance", note: "Real. From Latin <em>lambere</em>, to lick — the flame licks the surface." , ex: "A <em>lambent</em> glow came off the coals long after the flames died." , lvl: 2 },
  { w: "maunder", pos: "verb", def: "to talk ramblingly; to move about aimlessly", note: "Real. Not related to 'meander', despite the obvious suspicion." , ex: "He would <em>maunder</em> about the war for hours without ever reaching a point." , lvl: 2 },
  { w: "mellifluous", pos: "adjective", def: "sweet and smooth to listen to", note: "Real. Latin <em>mel</em> (honey) + <em>fluere</em> (to flow)." , ex: "Her <em>mellifluous</em> reading voice sold more audiobooks than the author's name did." , lvl: 1 },
  { w: "moiety", pos: "noun", def: "one of two parts into which something is divided", note: "Real, and still working in law and in chemistry." , ex: "Each <em>moiety</em> of the estate went to a different branch of the family." , lvl: 2 },
  { w: "nictitate", pos: "verb", def: "to blink", note: "Real. Many animals have a nictitating membrane — a third, transparent eyelid." , ex: "The hawk <em>nictitated</em> once, a pale membrane sweeping the eye clean." , lvl: 3 },
  { w: "noctambulist", pos: "noun", def: "a sleepwalker", note: "Real. Latin <em>nox</em> (night) + <em>ambulare</em> (to walk)." , ex: "As a child he was a <em>noctambulist</em>, and his parents put a bell on the front door." , lvl: 3 },
  { w: "obstreperous", pos: "adjective", def: "noisy and difficult to control", note: "Real. Latin <em>ob-</em> (against) + <em>strepere</em> (to make a racket)." , ex: "The class turned <em>obstreperous</em> the moment the substitute teacher appeared." , lvl: 1 },
  { w: "omphaloskepsis", pos: "noun", def: "contemplation of one's own navel", note: "Real, and genuinely in the dictionary." , ex: "The retreat was billed as reflection but amounted to three days of <em>omphaloskepsis</em>." , lvl: 3 },
  { w: "oneiric", pos: "adjective", def: "relating to dreams", note: "Real. Greek <em>oneiros</em>, dream." , ex: "The film has an <em>oneiric</em> logic — corridors that lead back into the same room." , lvl: 2 },
  { w: "palimpsest", pos: "noun", def: "a manuscript on which later writing covers earlier, erased writing", note: "Real. Parchment was costly, so scribes scraped it clean and started again." , ex: "The city is a <em>palimpsest</em>: Roman walls under Norman streets under Victorian brick." , lvl: 1 },
  { w: "panjandrum", pos: "noun", def: "a self-important official", note: "Real. Invented in 1755 inside a piece of nonsense written to test an actor's memory." , ex: "Some <em>panjandrum</em> from head office arrived to explain our own jobs to us." , lvl: 2 },
  { w: "pettifogger", pos: "noun", def: "a lawyer who quibbles over trivia", note: "Real, and usefully insulting since the 1500s." , ex: "The case was dragged out for years by a <em>pettifogger</em> arguing over commas." , lvl: 2 },
  { w: "pilcrow", pos: "noun", def: "the paragraph mark, &para;", note: "Real. That symbol has a name, and this is it." , ex: "Turn on formatting marks and every paragraph sprouts a <em>pilcrow</em>." , lvl: 3 },
  { w: "plangent", pos: "adjective", def: "loud and resonant, with a mournful tone", note: "Real. Usually said of bells, cellos and foghorns." , ex: "A <em>plangent</em> cello line carried the whole second act." , lvl: 3 },
  { w: "pleonasm", pos: "noun", def: "the use of more words than are needed", note: "Real. 'Free gift' and 'past history' are both pleonasms." , ex: "'Advance planning' is a <em>pleonasm</em>; all planning is done in advance." , lvl: 2 },
  { w: "propinquity", pos: "noun", def: "nearness in place, time or relationship", note: "Real. From Latin <em>prope</em>, near." , ex: "Their friendship began in mere <em>propinquity</em> — adjacent desks, nothing more." , lvl: 2 },
  { w: "ratiocination", pos: "noun", def: "the process of methodical reasoning", note: "Real. Poe used it for what his detective Dupin does." , ex: "Holmes's <em>ratiocination</em> turns a splash of mud into a confession." , lvl: 2 },
  { w: "recrudescence", pos: "noun", def: "the return of something unwelcome after a lull", note: "Real. From Latin for 'becoming raw again'." , ex: "Autumn brought a <em>recrudescence</em> of the cough he thought he had beaten." , lvl: 3 },
  { w: "salubrious", pos: "adjective", def: "health-giving; agreeable", note: "Real. From Latin <em>salus</em>, health." , ex: "The doctor prescribed a month in a more <em>salubrious</em> climate." , lvl: 1 },
  { w: "saturnine", pos: "adjective", def: "gloomy or sullen in temperament", note: "Real. Astrology blamed it on being born under Saturn." , ex: "Her <em>saturnine</em> brother sat through the whole wedding without lifting his eyes." , lvl: 2 },
  { w: "scintilla", pos: "noun", def: "a tiny trace or spark", note: "Real. Latin for spark, and the ancestor of 'scintillate'." , ex: "There was not a <em>scintilla</em> of evidence linking him to the theft." , lvl: 1 },
  { w: "skeuomorph", pos: "noun", def: "a design feature that imitates something from an older version", note: "Real. The shutter click on a silent phone camera is one." , ex: "The little floppy disk on the save button is a <em>skeuomorph</em> nobody under twenty recognises." , lvl: 3 },
  { w: "susurrus", pos: "noun", def: "a soft whispering or rustling sound", note: "Real, and the Latin imitates the sound itself." , ex: "A <em>susurrus</em> of paper ran through the hall as everyone turned the page at once." , lvl: 3 },
  { w: "thaumaturge", pos: "noun", def: "a worker of wonders or miracles", note: "Real. Greek <em>thauma</em>, marvel." , ex: "The village treated the new doctor as a <em>thaumaturge</em> rather than a scientist." , lvl: 3 },
  { w: "tmesis", pos: "noun", def: "the insertion of one word inside another", note: "Real. As in 'abso-blooming-lutely'." , ex: "'Abso-blooming-lutely' is <em>tmesis</em>, and Eliza Doolittle's finest hour of grammar." , lvl: 2 },
  { w: "troglodyte", pos: "noun", def: "a cave dweller; a person of unenlightened habits", note: "Real. Greek <em>trogle</em>, hole." , ex: "He called himself a <em>troglodyte</em> — three months underground, mapping the cave system." , lvl: 1 },
  { w: "uxorious", pos: "adjective", def: "excessively devoted to one's wife", note: "Real. From Latin <em>uxor</em>, wife." , ex: "So <em>uxorious</em> was the old man that he refused every invitation his wife declined." , lvl: 2 },
  { w: "vespertine", pos: "adjective", def: "of or occurring in the evening", note: "Real, and the exact counterpart of 'matutinal'." , ex: "The <em>vespertine</em> chorus of bats begins about twenty minutes after sunset." , lvl: 2 },
  { w: "wamble", pos: "verb", def: "to move unsteadily; of the stomach, to feel queasy", note: "Real, and the ancestor of 'wobble'." , ex: "The ferry pitched hard, and his stomach began to <em>wamble</em>." , lvl: 3 },
  { w: "zoetrope", pos: "noun", def: "a spinning drum whose slits make still pictures appear to move", note: "Real. A Victorian toy, and an ancestor of cinema." , ex: "A <em>zoetrope</em> on the nursery shelf turned twelve drawings into a galloping horse." , lvl: 2 },
  { w: "aglet", pos: "noun", def: "the small sheath at the end of a shoelace", note: "Real. It has a name, and this is it." , ex: "The <em>aglet</em> had come off, and threading the lace became a two-minute job." , lvl: 1 },
  { w: "zarf", pos: "noun", def: "a holder for a cup that has no handle", note: "Real. Originally an ornamented metal one from the Ottoman world." , ex: "The coffee arrived in a brass <em>zarf</em>, the glass inside far too hot to hold." , lvl: 3 },
  { w: "ferrule", pos: "noun", def: "the metal cap on the end of a stick or tool handle", note: "Real. Every walking stick and chisel has one." , ex: "The walking stick's rubber <em>ferrule</em> had worn through to the metal." , lvl: 2 },
  { w: "philtrum", pos: "noun", def: "the vertical groove between the nose and the upper lip", note: "Real. Greek for 'love charm'." , ex: "A drop of rain sat in the <em>philtrum</em> just above his lip." , lvl: 2 },
  { w: "tittle", pos: "noun", def: "the dot above a lowercase i or j", note: "Real. It is the tittle in 'not one jot or tittle'." , ex: "Handwriting analysts make much of where a writer puts the <em>tittle</em> over an i." , lvl: 1 },
  { w: "lunule", pos: "noun", def: "the pale crescent at the base of a fingernail", note: "Real. Latin for 'little moon'." , ex: "The <em>lunule</em> on her thumb was the only one still visible." , lvl: 3 },
  { w: "glabella", pos: "noun", def: "the smooth patch of forehead between the eyebrows", note: "Real, and standard anatomical vocabulary." , ex: "He pressed two fingers to his <em>glabella</em>, willing the headache away." , lvl: 2 },
  { w: "muntin", pos: "noun", def: "a strip separating panes of glass in a window", note: "Real. Every sash window has them." , ex: "Each <em>muntin</em> had to be repainted by hand, twelve panes to a window." , lvl: 3 },
  { w: "escutcheon", pos: "noun", def: "a shield bearing a coat of arms; also the plate around a keyhole", note: "Real. A blot on the escutcheon is a stain on the family name." , ex: "The brass <em>escutcheon</em> around the keyhole was worn bright by a century of use." , lvl: 1 },
  { w: "bumbershoot", pos: "noun", def: "an umbrella", note: "Real, if jocular. American, from 'umbrella' crossed with 'parachute'." , ex: "He set off into the drizzle under an enormous striped <em>bumbershoot</em>." , lvl: 1 },
  { w: "gubbins", pos: "noun", def: "odds and ends; a gadget whose name escapes you", note: "Real. British and thoroughly informal." , ex: "The drawer was full of <em>gubbins</em> — cables, adaptors and keys to nothing." , lvl: 1 },
  { w: "hornswoggle", pos: "verb", def: "to cheat or hoodwink", note: "Real. Nineteenth-century American, and a fine thing to be accused of." , ex: "The dealer tried to <em>hornswoggle</em> him over the mileage." , lvl: 2 },
  { w: "lollygag", pos: "verb", def: "to dawdle or fool about", note: "Real, and in print since the 1860s." , ex: "Stop <em>lollygagging</em> by the vending machine; the train leaves in four minutes." , lvl: 2 },
  { w: "mugwump", pos: "noun", def: "a person who stays aloof from party politics", note: "Real. From an Algonquian word meaning 'war leader'." , ex: "He remained a <em>mugwump</em> through three elections, refusing to endorse anyone." , lvl: 2 },
  { w: "skulduggery", pos: "noun", def: "underhanded or unscrupulous behaviour", note: "Real. Originally the Scots <em>sculduddery</em>." , ex: "The audit uncovered genuine <em>skulduggery</em> in the procurement office." , lvl: 1 },
  { w: "taradiddle", pos: "noun", def: "a petty lie; pretentious nonsense", note: "Real, and far too good a word to lose." , ex: "The excuse was a transparent <em>taradiddle</em> about a flat tyre." , lvl: 3 },
  { w: "woolgathering", pos: "noun", def: "aimless daydreaming", note: "Real. From the idle job of collecting wool snagged on hedges." , ex: "An afternoon of <em>woolgathering</em> at the window produced no work at all." , lvl: 2 },
  { w: "somnifuge", pos: "noun", def: "something that drives sleep away", note: "Real, if rare. Latin <em>somnus</em> (sleep) + <em>fugare</em> (to put to flight). A <em>soporific</em> does the opposite." , ex: "Strong coffee after nine is a reliable <em>somnifuge</em>." , lvl: 3 },
  { w: "yclept", pos: "adjective", def: "by the name of; called", note: "Real but archaic — the Middle English past participle of <em>clepe</em>, to call." , ex: "A knight <em>yclept</em> Gareth arrives in the third chapter and immediately loses his horse." , lvl: 3 },
  { w: "brouhaha", pos: "noun", def: "a noisy and overexcited reaction to something", note: "Real. French, and probably imitating the noise itself.", ex: "There was a brief <em>brouhaha</em> over the seating plan and then everyone sat down." , lvl: 1 },
  { w: "curmudgeon", pos: "noun", def: "a bad-tempered person, especially an old one", note: "Real, in print since 1577, origin unknown.", ex: "The building's resident <em>curmudgeon</em> kept every ball that landed in his garden." , lvl: 1 },
  { w: "debacle", pos: "noun", def: "a sudden and humiliating failure", note: "Real. French, originally the breaking up of ice on a river.", ex: "The launch was a <em>debacle</em>: no microphone, no slides and no chief executive." , lvl: 1 },
  { w: "doldrums", pos: "noun", def: "a state of stagnation or low spirits", note: "Real. Named for the belt of calm near the equator where sailing ships stalled.", ex: "Sales stayed in the <em>doldrums</em> until the weather turned." , lvl: 1 },
  { w: "ephemeral", pos: "adjective", def: "lasting for a very short time", note: "Real. Greek <em>ephemeros</em>, lasting a day — the mayfly's whole career.", ex: "Frost patterns on the window are <em>ephemeral</em>; they were gone by nine." , lvl: 1 },
  { w: "finagle", pos: "verb", def: "to obtain something by devious or dishonest means", note: "Real, American, from around 1920.", ex: "He <em>finagled</em> a seat at the front table without an invitation." , lvl: 1 },
  { w: "gauche", pos: "adjective", def: "lacking social grace; awkward", note: "Real. French for 'left', with all the prejudice that implies.", ex: "Asking what the flat cost struck everyone as <em>gauche</em>." , lvl: 1 },
  { w: "juggernaut", pos: "noun", def: "a huge, overwhelming force that cannot be stopped", note: "Real. From the Sanskrit <em>Jagannatha</em> and the great cart carried in his festival.", ex: "The small studio found itself competing with a <em>juggernaut</em>." , lvl: 1 },
  { w: "lackadaisical", pos: "adjective", def: "lacking enthusiasm or determination", note: "Real. From the old cry 'lack-a-day', meaning what a shame.", ex: "A <em>lackadaisical</em> second half cost them the match." , lvl: 1 },
  { w: "malarkey", pos: "noun", def: "meaningless talk; nonsense", note: "Real, American, first recorded in the 1920s.", ex: "He dismissed the entire forecast as <em>malarkey</em>." , lvl: 1 },
  { w: "nonplussed", pos: "adjective", def: "so surprised that one does not know how to react", note: "Real. Latin <em>non plus</em> — no more can be said.", ex: "She was frankly <em>nonplussed</em> to find her own portrait in the hallway." , lvl: 1 },
  { w: "obfuscate", pos: "verb", def: "to make something unclear or harder to understand", note: "Real. Latin <em>obfuscare</em>, to darken.", ex: "The footnotes seemed designed to <em>obfuscate</em> rather than explain." , lvl: 1 },
  { w: "panacea", pos: "noun", def: "a remedy said to cure every ill", note: "Real. Named for Panacea, the Greek goddess of universal remedy.", ex: "Broadband was sold to the village as a <em>panacea</em> for its problems." , lvl: 1 },
  { w: "quagmire", pos: "noun", def: "soft boggy ground; an awkward situation hard to escape", note: "Real, from the 1500s.", ex: "The contract dragged them into a legal <em>quagmire</em> lasting four years." , lvl: 1 },
  { w: "rambunctious", pos: "adjective", def: "uncontrollably boisterous", note: "Real, American, probably a reshaping of 'rumbustious'.", ex: "Two <em>rambunctious</em> spaniels met us at the gate." , lvl: 1 },
  { w: "serendipity", pos: "noun", def: "the happy accident of finding something good without looking for it", note: "Real. Coined by Horace Walpole in 1754 after a Persian fairy tale.", ex: "Their whole collaboration was <em>serendipity</em> — a missed train and one spare seat." , lvl: 1 },
  { w: "umbrage", pos: "noun", def: "offence or annoyance", note: "Real. Latin <em>umbra</em>, shade — you take offence as you take shadow.", ex: "He took <em>umbrage</em> at being introduced as the deputy." , lvl: 1 },
  { w: "aplomb", pos: "noun", def: "self-confidence and poise, especially in a difficult situation", note: "Real. French, originally meaning perfectly upright, as measured by a plumb line.", ex: "She handled the heckler with complete <em>aplomb</em>." , lvl: 1 },
  { w: "bamboozle", pos: "verb", def: "to fool or cheat someone", note: "Real, and already being complained about as slang in 1710.", ex: "They were <em>bamboozled</em> into paying twice for the same warranty." , lvl: 1 },
  { w: "cacophony", pos: "noun", def: "a harsh, discordant mixture of sounds", note: "Real. Greek <em>kakos</em> (bad) + <em>phone</em> (sound).", ex: "The orchestra tuning up is a <em>cacophony</em> that resolves into music." , lvl: 1 },
  { w: "effervescent", pos: "adjective", def: "bubbling; lively and enthusiastic", note: "Real. Latin <em>effervescere</em>, to boil up.", ex: "Her <em>effervescent</em> introduction woke the whole room." , lvl: 1 },
  { w: "flummox", pos: "verb", def: "to bewilder or perplex", note: "Real, English dialect, popularised by Dickens.", ex: "The final clue <em>flummoxed</em> even the setter's own family." , lvl: 2 },
  { w: "galvanize", pos: "verb", def: "to shock or excite someone into action", note: "Real. From Luigi Galvani, who made frogs' legs twitch with electricity.", ex: "The letter <em>galvanized</em> a committee that had done nothing for months." , lvl: 1 },
  { w: "abstruse", pos: "adjective", def: "difficult to understand; obscure", note: "Real. Latin <em>abstrusus</em>, hidden away.", ex: "His argument grew more <em>abstruse</em> with every slide." , lvl: 1 },
  { w: "cavil", pos: "verb", def: "to make petty objections", note: "Real. Latin <em>cavilla</em>, jeering.", ex: "Reviewers <em>cavilled</em> at the typeface and ignored the argument." , lvl: 1 },
  { w: "exiguous", pos: "adjective", def: "very small in amount; meagre", note: "Real. Latin <em>exiguus</em>, scanty.", ex: "The grant was so <em>exiguous</em> it barely covered postage." , lvl: 2 },
  { w: "hagiography", pos: "noun", def: "a biography that treats its subject as beyond criticism", note: "Real. Originally the writing of saints' lives.", ex: "The authorised life reads as <em>hagiography</em> and skips the trial entirely." , lvl: 3 },
  { w: "inchoate", pos: "adjective", def: "just begun; not yet fully formed", note: "Real. Latin <em>inchoare</em>, to begin.", ex: "The plan was still <em>inchoate</em> — three names and a map." , lvl: 2 },
  { w: "jejune", pos: "adjective", def: "naive and simplistic; also, dull", note: "Real. Latin <em>jejunus</em>, fasting or empty.", ex: "His politics struck her as <em>jejune</em>, all slogans and no arithmetic." , lvl: 1 },
  { w: "minatory", pos: "adjective", def: "threatening; menacing", note: "Real. Latin <em>minari</em>, to threaten — the root of 'menace'.", ex: "The final paragraph turned <em>minatory</em>, mentioning lawyers twice." , lvl: 3 },
  { w: "nugatory", pos: "adjective", def: "of no value or importance", note: "Real. Latin <em>nugae</em>, trifles.", ex: "The concession was <em>nugatory</em>: it changed nothing anyone cared about." , lvl: 2 },
  { w: "peripatetic", pos: "adjective", def: "travelling from place to place", note: "Real. From Aristotle's habit of teaching while walking about.", ex: "She had a <em>peripatetic</em> childhood — nine schools in eleven years." , lvl: 1 },
  { w: "quotidian", pos: "adjective", def: "daily; ordinary and everyday", note: "Real. Latin <em>quotidianus</em>, of every day.", ex: "The diary records the <em>quotidian</em>: bread, weather, a broken gate." , lvl: 2 },
  { w: "refulgent", pos: "adjective", def: "shining brilliantly", note: "Real. Latin <em>refulgere</em>, to flash back.", ex: "The hall was <em>refulgent</em> with candles by the time the guests arrived." , lvl: 2 },
  { w: "sedulous", pos: "adjective", def: "showing dedicated and careful diligence", note: "Real. Latin <em>sedulo</em>, sincerely, diligently.", ex: "Ten years of <em>sedulous</em> note-taking produced one very good book." , lvl: 3 },
  { w: "truculent", pos: "adjective", def: "eager to argue or fight; aggressively defiant", note: "Real. Latin <em>trux</em>, fierce.", ex: "He turned <em>truculent</em> the moment his figures were questioned." , lvl: 1 },
  { w: "vituperative", pos: "adjective", def: "bitter and abusive in language", note: "Real. Latin <em>vituperare</em>, to blame.", ex: "The exchange of letters grew steadily more <em>vituperative</em>." , lvl: 2 },
  { w: "welkin", pos: "noun", def: "the sky or the heavens", note: "Real but archaic — it survives in the phrase 'make the welkin ring'.", ex: "The choir sang loudly enough to make the <em>welkin</em> ring." , lvl: 1 },
  { w: "sylvan", pos: "adjective", def: "relating to woods or forests", note: "Real. Latin <em>silva</em>, wood.", ex: "They chose a <em>sylvan</em> spot for the house, entirely surrounded by beech." , lvl: 1 },
  { w: "adumbrate", pos: "verb", def: "to outline faintly; to foreshadow", note: "Real. Latin <em>adumbrare</em>, to sketch in shadow.", ex: "The opening chapter <em>adumbrates</em> a betrayal that arrives two hundred pages later." , lvl: 2 },
  { w: "cozen", pos: "verb", def: "to trick or deceive, especially by flattery", note: "Real, and a favourite of Shakespeare's.", ex: "He was <em>cozened</em> out of the deed by a man claiming to be a surveyor." , lvl: 2 },
  { w: "deracinate", pos: "verb", def: "to uproot; to remove from a natural environment", note: "Real. French <em>déraciner</em>, from <em>racine</em>, root.", ex: "Two wars had <em>deracinated</em> the family entirely." , lvl: 3 },
  { w: "execrable", pos: "adjective", def: "extremely bad", note: "Real. Latin <em>execrari</em>, to curse.", ex: "The coffee was <em>execrable</em> and the company worse." , lvl: 1 },
  { w: "gallivant", pos: "verb", def: "to roam about in search of pleasure", note: "Real, from the early 1800s.", ex: "He spent the inheritance <em>gallivanting</em> around the Mediterranean." , lvl: 1 },
  { w: "hoary", pos: "adjective", def: "greyish white with age; ancient and overfamiliar", note: "Real. Old English <em>har</em>, grey.", ex: "He opened with the same <em>hoary</em> joke he had used for thirty years." , lvl: 1 },
  { w: "importunate", pos: "adjective", def: "persistent to the point of annoyance in making demands", note: "Real. Latin <em>importunus</em>, troublesome.", ex: "An <em>importunate</em> gull followed us the length of the pier." , lvl: 1 },
  { w: "lugubrious", pos: "adjective", def: "looking or sounding sad and dismal", note: "Real. Latin <em>lugere</em>, to mourn.", ex: "The <em>lugubrious</em> hound watched us eat without blinking." , lvl: 1 },
  { w: "bombinate", pos: "verb", def: "to buzz or hum", note: "Real, if rare. Latin <em>bombinare</em>.", ex: "Somewhere above the ceiling a trapped wasp <em>bombinated</em> all afternoon." , lvl: 3 },
  { w: "objurgate", pos: "verb", def: "to rebuke severely", note: "Real. Latin <em>objurgare</em>, to chide.", ex: "The referee <em>objurgated</em> both captains and restarted the clock." , lvl: 3 },
  { w: "lucubration", pos: "noun", def: "study or writing done late at night", note: "Real. Latin <em>lucubrare</em>, to work by lamplight.", ex: "The preface thanks his wife for tolerating years of <em>lucubration</em>." , lvl: 3 }
];

const FAKE_WORDS = [
  { w: "crumbulent", pos: "adjective", def: "tending to shed crumbs; liable to disintegrate when handled", note: "Invented. The word you want is <em>friable</em>." , lvl: 3 },
  { w: "blandiculous", pos: "adjective", def: "amusing only in a mild, entirely inoffensive way", note: "Invented — a portmanteau built to sound like it belongs." , lvl: 3 },
  { w: "umbriculate", pos: "verb", def: "to shelter something beneath a small canopy", note: "Invented. <em>Umbriferous</em> (shade-giving) is the real relative." , lvl: 3 },
  { w: "hubrilate", pos: "verb", def: "to boast about oneself in the guise of a complaint", note: "Invented. English already covers this with <em>humblebrag</em>." , lvl: 3 },
  { w: "vellichor", pos: "noun", def: "the strange wistfulness of second-hand bookshops", note: "Invented — coined for The Dictionary of Obscure Sorrows in 2012. Beautiful, but never a dictionary word." , lvl: 3 },
  { w: "glissamer", pos: "noun", def: "the thin film of ice that forms on a puddle overnight", note: "Invented. Real names for it include <em>shell ice</em> and <em>cat ice</em>." , lvl: 3 },
  { w: "fennelwick", pos: "noun", def: "the charred tip of a candle wick", note: "Invented. That charred tip is the <em>snuff</em>." , lvl: 2 },
  { w: "pratterling", pos: "noun", def: "a child who chatters without pause", note: "Invented from 'prattle' — convincing, but not a word." , lvl: 2 },
  { w: "rasplinth", pos: "noun", def: "the rough, unfinished stone base of a column", note: "Invented. <em>Plinth</em> is real; the rasp is ours." , lvl: 2 },
  { w: "skelvish", pos: "adjective", def: "thin and sickly in appearance", note: "Invented. Try <em>etiolated</em>, or just 'peaky'." , lvl: 2 },
  { w: "wintlebeck", pos: "noun", def: "a stream that flows only after heavy rain", note: "Invented — and a shame, because the real word is the lovely <em>winterbourne</em>." , lvl: 1 },
  { w: "thrumbleset", pos: "noun", def: "the low vibration felt through the floor of a moving train", note: "Invented, from 'thrum'." , lvl: 1 },
  { w: "norvient", pos: "adjective", def: "turned away from the prevailing wind", note: "Invented. Sailors just say <em>leeward</em>." , lvl: 3 },
  { w: "sprocketine", pos: "noun", def: "a single tooth on a gear wheel", note: "Invented. One tooth is a <em>cog</em>." , lvl: 2 },
  { w: "delphinate", pos: "verb", def: "to arch the back while entering the water in a dive", note: "Invented, from Latin <em>delphinus</em>, dolphin." , lvl: 3 },
  { w: "obelquin", pos: "noun", def: "a scribe's mark indicating a doubtful passage", note: "Invented. The genuine mark is an <em>obelus</em> (†)." , lvl: 3 },
  { w: "lorrimund", pos: "noun", def: "a hedge maze planted for walking meditation", note: "Invented. You're thinking of a <em>labyrinth</em>." , lvl: 2 },
  { w: "clatterfaust", pos: "noun", def: "a person who habitually slams cupboard doors", note: "Invented — German-ish suffix, entirely fictional." , lvl: 1 },
  { w: "gremulous", pos: "adjective", def: "faintly and persistently resentful", note: "Invented. You're half-remembering <em>querulous</em> and <em>tremulous</em>." , lvl: 3 },
  { w: "yaspernet", pos: "noun", def: "a fine mesh used for straining honey", note: "Invented. Beekeepers use a plain honey strainer." , lvl: 1 },
  { w: "brimsalop", pos: "noun", def: "the crust of salt left on the rim of a glass", note: "Invented." , lvl: 1 },
  { w: "tundlish", pos: "adjective", def: "slow-witted as a result of cold", note: "Invented." , lvl: 2 },
  { w: "quillevant", pos: "noun", def: "an ornamental feather worn in a hat", note: "Invented. Real options: <em>aigrette</em>, or a <em>panache</em>." , lvl: 3 },
  { w: "plinthery", pos: "noun", def: "decorative stonework running along the base of a wall", note: "Invented — the -ery is doing a lot of work." , lvl: 2 },
  { w: "serrivagant", pos: "adjective", def: "given to wandering among hills", note: "Invented. The rare-but-real one is <em>montivagant</em>." , lvl: 3 },
  { w: "cathomancy", pos: "noun", def: "divination by observing the behaviour of cats", note: "Invented — though divination by cat is real and is called <em>ailuromancy</em>." , lvl: 3 },
  { w: "flennick", pos: "noun", def: "a small blunt tool for prying open shellfish", note: "Invented. It's a <em>shucking knife</em>." , lvl: 2 },
  { w: "juvantine", pos: "adjective", def: "impulsive in the manner of the young", note: "Invented. <em>Juvenescent</em> is the real word." , lvl: 3 },
  { w: "gorbelt", pos: "noun", def: "the ring of cloud that forms around a mountain peak", note: "Invented. Meteorologists call it a <em>banner cloud</em>." , lvl: 1 },
  { w: "nixiate", pos: "verb", def: "to rub out a written mark", note: "Invented. <em>Expunge</em> or <em>efface</em> will do." , lvl: 3 },
  { w: "murkling", pos: "noun", def: "the dusk of a foggy evening", note: "Invented — it sounds like Old English, but it isn't." , lvl: 1 },
  { w: "quarnstile", pos: "noun", def: "a stone step set into a wall to allow crossing", note: "Invented. That is simply a <em>stile</em>." , lvl: 2 },
  { w: "bellamute", pos: "adjective", def: "silent but visibly angry", note: "Invented." , lvl: 3 },
  { w: "wemblish", pos: "adjective", def: "unsteady on the feet", note: "Invented — although <em>wamble</em>, to move unsteadily, is real." , lvl: 2 },
  { w: "hushpine", pos: "noun", def: "a sudden lull in conversation around a table", note: "Invented. The nearest real thing is the folk phrase 'an angel passing over'." , lvl: 1 },
  { w: "glaverwing", pos: "noun", def: "a moth that flies only at first light", note: "Invented — no such moth, no such word." , lvl: 1 },
  { w: "torpiculous", pos: "adjective", def: "sluggish and heavy after a large meal", note: "Invented. <em>Postprandial torpor</em> is the real (two-word) answer." , lvl: 3 },
  { w: "varnicle", pos: "noun", def: "the dimple in the base of a wine bottle", note: "Invented. That dimple is the <em>punt</em>." , lvl: 2 },
  { w: "veritude", pos: "noun", def: "the quality of sounding true without being true", note: "Invented — which is either ironic or fitting. <em>Verisimilitude</em> is the real one." , lvl: 3 },
  { w: "pluviscent", pos: "adjective", def: "smelling of rain that has not yet fallen", note: "Invented. The smell after rain does have a name though — <em>petrichor</em>." , lvl: 3 },
  { w: "tenebrile", pos: "adjective", def: "visible only in dim light", note: "Invented. <em>Tenebrous</em>, meaning dark or shadowy, is real." , lvl: 3 },
  { w: "fenestrine", pos: "adjective", def: "of light cast through a window", note: "Invented, from the real Latin <em>fenestra</em>, window." , lvl: 3 },
  { w: "verdurine", pos: "adjective", def: "of the green light beneath summer leaves", note: "Invented. <em>Verdure</em>, lush greenery, is real." , lvl: 3 },
  { w: "glinth", pos: "noun", def: "the sliver of light beneath a closed door", note: "Invented — no such word, and no such name for it." , lvl: 1 },
  { w: "flisken", pos: "noun", def: "the small gust of air let in by an opening door", note: "Invented." , lvl: 1 },
  { w: "wrindle", pos: "verb", def: "to crease cloth by gripping it", note: "Invented, from 'wrinkle' by way of nowhere." , lvl: 2 },
  { w: "tarnicle", pos: "noun", def: "the metal loop on a dog's collar", note: "Invented. That loop is just a D-ring." , lvl: 1 },
  { w: "brindlewick", pos: "noun", def: "the frayed end of a rope", note: "Invented. Sailors would say the rope has <em>fagged out</em>." , lvl: 1 },
  { w: "clabberwort", pos: "noun", def: "a weed that grows only on freshly turned soil", note: "Invented, though it sounds like something in a herbal." , lvl: 1 },
  { w: "mundicle", pos: "noun", def: "a small everyday object that has no name of its own", note: "Invented — and self-defeating, since it would then have one." , lvl: 2 },
  { w: "sobrement", pos: "noun", def: "the quiet that follows laughter", note: "Invented." , lvl: 2 },
  { w: "quillimet", pos: "noun", def: "the notch cut into the nib of a quill pen", note: "Invented. That cut is simply the <em>slit</em>." , lvl: 1 },
  { w: "hesperand", pos: "noun", def: "the last bird heard singing at dusk", note: "Invented, from Hesperus, the evening star." , lvl: 2 },
  { w: "morrowsome", pos: "adjective", def: "of a problem that looks smaller in the morning", note: "Invented." , lvl: 2 },
  { w: "gallimander", pos: "verb", def: "to wander off the point while telling a story", note: "Invented. <em>Maunder</em> already means roughly this, and is real." , lvl: 2 },
  { w: "crandle", pos: "verb", def: "to walk carefully over loose stones", note: "Invented." , lvl: 2 },
  { w: "rimswale", pos: "noun", def: "the ring a wet glass leaves on wood", note: "Invented. There is no accepted word for it, which is a shame." , lvl: 1 },
  { w: "drindle", pos: "verb", def: "to run slowly down a surface, of a liquid", note: "Invented — you are thinking of <em>trickle</em> or <em>dribble</em>." , lvl: 2 },
  { w: "blenkish", pos: "adjective", def: "pale from want of sleep", note: "Invented." , lvl: 2 },
  { w: "gorminate", pos: "verb", def: "to stare into the middle distance while thinking", note: "Invented — though <em>gormless</em>, its apparent relative, is real." , lvl: 2 },
  { w: "quaverling", pos: "noun", def: "a voice made unsteady by cold rather than nerves", note: "Invented." , lvl: 2 },
  { w: "snorrick", pos: "noun", def: "a knot pulled too tight to undo", note: "Invented." , lvl: 1 },
  { w: "umberwash", pos: "noun", def: "the brown light of a dust storm", note: "Invented, from the pigment umber." , lvl: 3 },
  { w: "murgle", pos: "verb", def: "to laugh with the mouth closed", note: "Invented." , lvl: 2 },
  { w: "glomber", pos: "verb", def: "to climb awkwardly, on hands and knees", note: "Invented — <em>clamber</em> is the real one." , lvl: 2 },
  { w: "plensive", pos: "adjective", def: "quietly regretful", note: "Invented. <em>Pensive</em> is real and close enough to fool most people." , lvl: 3 },
  { w: "cindrous", pos: "adjective", def: "resembling cold ash", note: "Invented. <em>Cinereous</em>, ash-grey, is real." , lvl: 3 },
  { w: "lumenette", pos: "noun", def: "the small light left burning for a child", note: "Invented. It is a night light." , lvl: 2 },
  { w: "gravelock", pos: "noun", def: "the sound of gravel underfoot", note: "Invented." , lvl: 1 },
  { w: "sallowick", pos: "noun", def: "the pale band of skin left by a removed ring", note: "Invented." , lvl: 2 },
  { w: "windleset", pos: "noun", def: "the pattern wind leaves on dry sand", note: "Invented. Geologists call those <em>ripple marks</em>." , lvl: 1 },
  { w: "yarnicle", pos: "noun", def: "a small tangle in a ball of wool", note: "Invented." , lvl: 1 },
  { w: "dawnling", pos: "noun", def: "the first bird call before sunrise", note: "Invented — the whole performance is the <em>dawn chorus</em>, which is real." , lvl: 1 },
  { w: "mirthling", pos: "noun", def: "a laugh that escapes at the wrong moment", note: "Invented." , lvl: 1 },
  { w: "scrimble", pos: "verb", def: "to write hurriedly and illegibly", note: "Invented. <em>Scribble</em> got there first." , lvl: 2 },
  { w: "felloquy", pos: "noun", def: "a conversation between two people who dislike each other", note: "Invented. <em>Colloquy</em>, a formal conversation, is real." , lvl: 3 },
  { w: "duskerly", pos: "adverb", def: "in the manner of failing light", note: "Invented." , lvl: 2 },
  { w: "glimmerwick", pos: "noun", def: "the last inch of a burning candle", note: "Invented. The stub is a <em>candle end</em>, unglamorously." , lvl: 1 },
  { w: "hushet", pos: "noun", def: "the small silence between two sounds", note: "Invented." , lvl: 1 },
  { w: "sundrift", pos: "noun", def: "a patch of sunlight that moves across a floor", note: "Invented." , lvl: 1 },
  { w: "tacitude", pos: "noun", def: "the habit of saying very little", note: "Invented. <em>Taciturnity</em> is the real word, and cats have it." , lvl: 3 },
  { w: "wintermark", pos: "noun", def: "the ring in a tree left by a hard winter", note: "Invented. Those are simply growth rings, read by <em>dendrochronology</em>." , lvl: 1 },
  { w: "zephyrine", pos: "adjective", def: "of a breeze too slight to move a leaf", note: "Invented. <em>Zephyr</em>, a gentle west wind, is real." , lvl: 2 },
  { w: "cloudle", pos: "verb", def: "to gather slowly, the way cloud does", note: "Invented." , lvl: 2 },
  { w: "frostling", pos: "noun", def: "the first frost of the year", note: "Invented." , lvl: 1 },
  { w: "lanterling", pos: "noun", def: "a moth circling a lamp", note: "Invented." , lvl: 1 },
  { w: "bellhollow", pos: "noun", def: "the pause after a bell stops ringing", note: "Invented." , lvl: 1 },
  { w: "rainwick", pos: "noun", def: "the drip from an eave after the rain has stopped", note: "Invented." , lvl: 1 },
  { w: "shimwrack", pos: "noun", def: "the heat haze that hangs above a road", note: "Invented. That shimmer is a <em>mirage</em>." , lvl: 1 },
  { w: "petrilune", pos: "noun", def: "the moon seen through mist", note: "Invented." , lvl: 2 },
  { w: "lattermorn", pos: "noun", def: "the hour of the morning after the rush is over", note: "Invented." , lvl: 1 },
  { w: "sundle", pos: "verb", def: "to divide something into unequal parts", note: "Invented." , lvl: 2 },
  { w: "gleamsome", pos: "adjective", def: "catching the light in a way that draws the eye", note: "Invented." , lvl: 2 },
  { w: "kettlefret", pos: "noun", def: "the impatience felt while waiting for a kettle to boil", note: "Invented — a compound with no dictionary behind it." , lvl: 1 },
  { w: "sockdrift", pos: "noun", def: "the slow migration of socks to the foot of the bed", note: "Invented." , lvl: 1 },
  { w: "puddlewink", pos: "noun", def: "the flash of light thrown off a puddle by passing headlights", note: "Invented." , lvl: 1 },
  { w: "crumbfall", pos: "noun", def: "the spray of crumbs from a torn croissant", note: "Invented." , lvl: 1 },
  { w: "doorwhisper", pos: "noun", def: "the sound of a door brushing over carpet", note: "Invented." , lvl: 1 },
  { w: "spoonwake", pos: "noun", def: "the swirl left turning in tea after stirring", note: "Invented." , lvl: 1 },
  { w: "lidhuff", pos: "noun", def: "the puff of air released by opening a jar", note: "Invented." , lvl: 1 },
  { w: "pocketmuddle", pos: "noun", def: "the tangle of objects at the bottom of a coat pocket", note: "Invented." , lvl: 1 },
  { w: "blanketcreep", pos: "noun", def: "the gradual loss of blanket to the other sleeper", note: "Invented." , lvl: 1 },
  { w: "bootknock", pos: "noun", def: "the knock of boots against a step to shed mud", note: "Invented." , lvl: 1 },
  { w: "lampfleck", pos: "noun", def: "the shadow a moth throws on a lit ceiling", note: "Invented." , lvl: 1 },
  { w: "stairhitch", pos: "noun", def: "the stumble caused by expecting one more step", note: "Invented." , lvl: 1 },
  { w: "mugring", pos: "noun", def: "the ring of coffee dried inside an unwashed mug", note: "Invented. On the table it would be a <em>ring stain</em>; in the mug it is nothing at all." , lvl: 1 },
  { w: "brimsome", pos: "adjective", def: "filled to the point of spilling", note: "Invented. <em>Brimful</em> is the real one." , lvl: 2 },
  { w: "glinter", pos: "verb", def: "to shine in short irregular flashes", note: "Invented — you are hearing <em>glint</em> and <em>glitter</em> at once." , lvl: 2 },
  { w: "hushling", pos: "noun", def: "a child who is unusually quiet in company", note: "Invented." , lvl: 2 },
  { w: "nettleish", pos: "adjective", def: "mildly and persistently irritating", note: "Invented. <em>Nettlesome</em>, which means exactly this, is real." , lvl: 2 },
  { w: "plundersome", pos: "adjective", def: "inclined to take what has not been offered", note: "Invented." , lvl: 2 },
  { w: "rumplish", pos: "adjective", def: "creased from having been slept in", note: "Invented — <em>rumpled</em> does the job." , lvl: 2 },
  { w: "slitherwise", pos: "adverb", def: "sideways, in order to pass someone in a narrow space", note: "Invented." , lvl: 2 },
  { w: "wanderling", pos: "noun", def: "a person who habitually takes the long way home", note: "Invented." , lvl: 2 },
  { w: "yawnsome", pos: "adjective", def: "tending to induce yawning", note: "Invented. <em>Soporific</em> is real and does it better." , lvl: 2 },
  { w: "flustersome", pos: "adjective", def: "apt to cause flustering", note: "Invented." , lvl: 2 },
  { w: "gloamish", pos: "adjective", def: "having the quality of late dusk", note: "Invented — although <em>gloaming</em>, the twilight itself, is entirely real." , lvl: 2 },
  { w: "mizzlewise", pos: "adverb", def: "in the manner of fine drifting rain", note: "Invented. <em>Mizzle</em>, that sort of rain, is a real word." , lvl: 2 },
  { w: "crinkleward", pos: "adverb", def: "in the direction of an existing fold", note: "Invented." , lvl: 2 },
  { w: "ferulent", pos: "adjective", def: "fitted with a metal tip or cap", note: "Invented — but <em>ferrule</em>, the metal cap itself, is real." , lvl: 3 },
  { w: "lapidine", pos: "adjective", def: "having the nature or coldness of stone", note: "Invented. <em>Lapidary</em> is the real relative." , lvl: 3 },
  { w: "gelidine", pos: "adjective", def: "of a chill that comes up from stone", note: "Invented, from the real Latin <em>gelidus</em>, icy." , lvl: 3 },
  { w: "murmurine", pos: "adjective", def: "of a sound just below the threshold of hearing", note: "Invented." , lvl: 3 },
  { w: "crepitine", pos: "adjective", def: "of the sound of many small breakages", note: "Invented. <em>Crepitate</em>, to crackle, is real." , lvl: 3 },
  { w: "pellucine", pos: "adjective", def: "of water clear enough to show its bed", note: "Invented. <em>Pellucid</em> is the real word." , lvl: 3 },
  { w: "rivulent", pos: "adjective", def: "marked by small channels, as sand is by a retreating tide", note: "Invented." , lvl: 3 },
  { w: "saporine", pos: "adjective", def: "of a taste that cannot quite be named", note: "Invented, though <em>sapor</em>, a distinctive flavour, is real." , lvl: 3 },
  { w: "umbrilious", pos: "adjective", def: "casting more shade than its size would suggest", note: "Invented." , lvl: 3 },
  { w: "brumescent", pos: "adjective", def: "of the first mist of the winter", note: "Invented — <em>brumal</em>, belonging to winter, is real." , lvl: 3 },
  { w: "cavernine", pos: "adjective", def: "of the echo particular to a cave", note: "Invented. <em>Cavernous</em> is real." , lvl: 3 },
  { w: "tallowine", pos: "adjective", def: "of the smell of a just-extinguished candle", note: "Invented, from tallow. The smell is real; the word is not." , lvl: 3 },
  { w: "obliquine", pos: "adjective", def: "of light that arrives at a low angle", note: "Invented." , lvl: 3 },
  { w: "quiescine", pos: "adjective", def: "of the stillness that follows hard effort", note: "Invented. <em>Quiescent</em>, meaning inactive or at rest, is real." , lvl: 3 },
  { w: "vesperine", pos: "adjective", def: "of the hour when lamps are first lit", note: "Invented, and one letter from <em>vespertine</em>, which is real and means of the evening." , lvl: 3 },
  { w: "noctulent", pos: "adjective", def: "wakeful late into the night", note: "Invented." , lvl: 3 },
  { w: "hibernine", pos: "adjective", def: "of the sleepiness brought on by a warm room", note: "Invented." , lvl: 3 },
  { w: "tacitine", pos: "adjective", def: "of a silence agreed on without discussion", note: "Invented. That silence is <em>tacit</em>, which is real." , lvl: 3 },
  { w: "lentine", pos: "adjective", def: "moving so slowly the movement cannot be seen", note: "Invented." , lvl: 3 }
];
