/* Lexicon Artist — the word bank.
 *
 * Every entry: { w: word, pos: part of speech, def: definition, real: true|false, note: shown after the guess }
 *
 * REAL entries are genuine English words with genuine definitions.
 * FAKE entries are inventions — plausible shapes, plausible meanings, no dictionary.
 * To add words, just append to either array. The game picks 5 real + 5 fake per round.
 */

const REAL_WORDS = [
  { w: "borborygmus", pos: "noun", def: "the rumbling noise made by gas moving through the intestines", note: "Real. From Greek <em>borborygmos</em> — the word is basically the sound." },
  { w: "petrichor", pos: "noun", def: "the pleasant earthy smell that follows rain falling on dry ground", note: "Real. Coined in 1964 by two Australian scientists, from Greek <em>petra</em> (stone) + <em>ichor</em> (the fluid in the veins of the gods)." },
  { w: "defenestration", pos: "noun", def: "the act of throwing someone or something out of a window", note: "Real. The Defenestrations of Prague (1419 and 1618) helped touch off two wars." },
  { w: "absquatulate", pos: "verb", def: "to leave abruptly; to make off with something", note: "Real. Nineteenth-century American mock-Latin — the frontier press loved inventing words that sounded classical." },
  { w: "gallimaufry", pos: "noun", def: "a confused jumble or medley of things", note: "Real. It started life as a stew made of whatever was left in the kitchen." },
  { w: "mumpsimus", pos: "noun", def: "a stubborn adherence to a habit or notion even after it is shown to be wrong", note: "Real. From a priest who kept misreading the Latin <em>sumpsimus</em> as <em>mumpsimus</em> and refused to be corrected." },
  { w: "sesquipedalian", pos: "adjective", def: "(of a word) very long; given to using long words", note: "Real, and self-demonstrating. Literally 'a foot and a half long', from Horace." },
  { w: "tergiversate", pos: "verb", def: "to make conflicting or evasive statements; to switch loyalties", note: "Real. Latin <em>tergum</em> (back) + <em>versare</em> (to turn) — to turn your back." },
  { w: "ultracrepidarian", pos: "noun", def: "a person who gives opinions on matters beyond their knowledge", note: "Real. From a cobbler who criticised a painting above the shoe line: <em>ne sutor ultra crepidam</em>." },
  { w: "widdershins", pos: "adverb", def: "in a direction contrary to the sun's course; counterclockwise", note: "Real. Scots, and long thought to be unlucky." },
  { w: "zugzwang", pos: "noun", def: "a position in which any move a player can make will worsen it", note: "Real — a chess term borrowed whole from German: 'compulsion to move'." },
  { w: "quidnunc", pos: "noun", def: "an inquisitive, gossiping person; a busybody", note: "Real. From the Latin <em>quid nunc?</em> — 'what now?'" },
  { w: "rebarbative", pos: "adjective", def: "unattractive and objectionable; repellent", note: "Real. From French — literally to stand beard-to-beard with someone." },
  { w: "snollygoster", pos: "noun", def: "a shrewd, unprincipled person, especially a politician", note: "Real. Nineteenth-century American, and overdue for a comeback." },
  { w: "velleity", pos: "noun", def: "a wish or inclination too slight to lead to any action", note: "Real. From Latin <em>velle</em>, to wish. The word for wanting to go to the gym." },
  { w: "floccinaucinihilipilification", pos: "noun", def: "the act of estimating something as worthless", note: "Real, if barely used — it was assembled in the 18th century out of four Latin words all meaning 'trifle'." },
  { w: "cachinnate", pos: "verb", def: "to laugh loudly or immoderately", note: "Real. Latin <em>cachinnare</em>, to guffaw." },
  { w: "brontide", pos: "noun", def: "a low muffled rumbling like distant thunder", note: "Real. From Greek <em>bronte</em>, thunder — the same root as the dinosaur." },
  { w: "limerence", pos: "noun", def: "the state of being obsessively infatuated with another person", note: "Real. Coined by the psychologist Dorothy Tennov in the 1970s and now in wide use." },
  { w: "deipnosophist", pos: "noun", def: "a person skilled in table talk", note: "Real. From Athenaeus's third-century work <em>The Deipnosophists</em> — dinner guests who talk beautifully." },
  { w: "mondegreen", pos: "noun", def: "a misheard word or phrase, especially in a song lyric", note: "Real. Coined in 1954 from 'laid him on the green' misheard as 'Lady Mondegreen'." },
  { w: "callipygian", pos: "adjective", def: "having shapely buttocks", note: "Real. Greek <em>kallos</em> (beauty) + <em>pyge</em>. There is a famous statue named for it." },
  { w: "bibulous", pos: "adjective", def: "excessively fond of drinking alcohol; also, absorbent", note: "Real. Latin <em>bibere</em>, to drink — the same root as 'imbibe'." },
  { w: "jentacular", pos: "adjective", def: "relating to breakfast", note: "Real, if archaic. From Latin <em>jentaculum</em>, the first meal of the day." },
  { w: "kakistocracy", pos: "noun", def: "government by the worst or least qualified people", note: "Real. Greek <em>kakistos</em>, worst. In use since the 1600s." },
  { w: "matutinal", pos: "adjective", def: "of or occurring in the morning", note: "Real. The opposite number is 'vespertine', of the evening." },
  { w: "obnubilate", pos: "verb", def: "to darken, dim, or obscure", note: "Real. Latin <em>nubes</em>, cloud — literally to cloud over." },
  { w: "pandiculation", pos: "noun", def: "the stretching and yawning that accompanies waking", note: "Real, and used in medicine. Cats are experts." },
  { w: "quockerwodger", pos: "noun", def: "a wooden puppet on strings; hence a politician controlled by someone else", note: "Real Victorian slang. Yes, really." },
  { w: "rodomontade", pos: "noun", def: "boastful or inflated talk", note: "Real. From Rodomonte, a swaggering braggart in Italian romance." },
  { w: "tatterdemalion", pos: "noun", def: "a person in ragged clothing", note: "Real, first recorded in the early 1600s." },
  { w: "usufruct", pos: "noun", def: "the legal right to use and enjoy the profits of property belonging to another", note: "Real. Straight out of Roman law and still live in modern civil codes." },
  { w: "yaffle", pos: "noun", def: "a green woodpecker", note: "Real British dialect, imitating the bird's laughing call." },
  { w: "agelast", pos: "noun", def: "a person who never laughs", note: "Real. Greek <em>a-</em> (not) + <em>gelan</em> (to laugh)." },
  { w: "bloviate", pos: "verb", def: "to speak or write at length in a pompous, empty way", note: "Real American coinage, forever associated with President Warren G. Harding." },
  { w: "hebetude", pos: "noun", def: "dullness of mind; mental lethargy", note: "Real. Latin <em>hebes</em>, blunt." },
  { w: "incunabula", pos: "noun", def: "books printed before 1501; by extension, the earliest stages of something", note: "Real. Latin for 'swaddling clothes' — the infancy of printing." },
  { w: "fuliginous", pos: "adjective", def: "sooty; of the colour of soot", note: "Real. Latin <em>fuligo</em>, soot." },
  { w: "crepuscular", pos: "adjective", def: "of or resembling twilight; (of animals) active at dawn and dusk", note: "Real. Deer, rabbits and mosquitoes are all crepuscular." },
  { w: "lachrymose", pos: "adjective", def: "tearful, or inclined to produce tears", note: "Real. Latin <em>lacrima</em>, tear." },
  { w: "anserine", pos: "adjective", def: "of or resembling a goose; hence, silly", note: "Real. Latin <em>anser</em>, goose — the bird equivalent of 'bovine'." },
  { w: "scrimshaw", pos: "noun", def: "carved or engraved work in whalebone or ivory, made by sailors", note: "Real. A whaling-ship craft from the 1800s." },
  { w: "epizeuxis", pos: "noun", def: "the immediate repetition of a word for emphasis", note: "Real — a rhetorical figure. 'Never, never, never give up.'" },
  { w: "nyctalopia", pos: "noun", def: "night blindness; poor vision in low light", note: "Real, and a genuine medical diagnosis, often from vitamin A deficiency." },
  { w: "zoanthropy", pos: "noun", def: "the delusion that one has become an animal", note: "Real, an old psychiatric term. Lycanthropy is the wolf-specific version." },
  { w: "abecedarian", pos: "noun", def: "a person learning the alphabet; a beginner in any subject", note: "Real. Named for the first four letters — A, B, C, D." },
  { w: "aeolian", pos: "adjective", def: "produced or carried by the wind", note: "Real. From Aeolus, keeper of the winds. An aeolian harp is played by the breeze alone." },
  { w: "apotropaic", pos: "adjective", def: "intended to ward off evil", note: "Real. Horseshoes over doorways and gargoyles on churches are both apotropaic." },
  { w: "autochthonous", pos: "adjective", def: "native to the place where it is found", note: "Real. Greek <em>autos</em> (self) + <em>chthon</em> (earth) — sprung from the ground itself." },
  { w: "bezoar", pos: "noun", def: "a hard mass of undigested material found in the stomach", note: "Real. For centuries it was believed to be an antidote to every poison." },
  { w: "blatherskite", pos: "noun", def: "a person who talks at great length without making sense", note: "Real. Scots by birth, and popular in America since the Revolution." },
  { w: "brumal", pos: "adjective", def: "belonging to or occurring in winter", note: "Real. From Latin <em>bruma</em>, the winter solstice." },
  { w: "cacoethes", pos: "noun", def: "an irresistible urge to do something inadvisable", note: "Real. Greek for a bad habit. <em>Cacoethes scribendi</em> is the incurable itch to write." },
  { w: "caliginous", pos: "adjective", def: "misty, dim, obscure", note: "Real. From Latin <em>caligo</em>, mist." },
  { w: "chiaroscuro", pos: "noun", def: "the arrangement of light and shade in a picture", note: "Real. Italian for light-dark. Caravaggio built a career on it." },
  { w: "clerisy", pos: "noun", def: "the learned class taken as a whole", note: "Real. Coined by Samuel Taylor Coleridge, who felt England needed one." },
  { w: "collywobbles", pos: "noun", def: "stomach pain, or a feeling of nervousness", note: "Real. Probably a playful mangling of <em>cholera morbus</em>." },
  { w: "concinnity", pos: "noun", def: "elegant harmony in the way parts are arranged", note: "Real. A favourite term of Cicero's admirers." },
  { w: "crapulous", pos: "adjective", def: "suffering the effects of too much drink", note: "Real. From Latin <em>crapula</em>, intoxication." },
  { w: "desuetude", pos: "noun", def: "a state of disuse", note: "Real. Laws nobody bothers to enforce are said to fall into desuetude." },
  { w: "eldritch", pos: "adjective", def: "weird, eerie, unearthly", note: "Real. Scots, and the reason so much horror fiction sounds Scottish." },
  { w: "embrocation", pos: "noun", def: "a liquid rubbed into the body to relieve aches", note: "Real. Standard issue in every nineteenth-century medicine cabinet." },
  { w: "farrago", pos: "noun", def: "a confused mixture", note: "Real. Latin for mixed fodder fed to cattle." },
  { w: "fissiparous", pos: "adjective", def: "inclined to split into factions", note: "Real. Biology got it first, for cells that reproduce by dividing." },
  { w: "flibbertigibbet", pos: "noun", def: "a frivolous, flighty person", note: "Real. It began as the name of a devil in <em>King Lear</em>." },
  { w: "frangible", pos: "adjective", def: "easily broken; fragile", note: "Real. Same root as 'fracture'." },
  { w: "gasconade", pos: "noun", def: "extravagant boasting", note: "Real. From Gascony, whose people had a reputation for exactly that." },
  { w: "gormless", pos: "adjective", def: "lacking sense or initiative", note: "Real. From an old northern English word, <em>gaum</em>, meaning understanding." },
  { w: "haruspex", pos: "noun", def: "a Roman priest who read omens in the entrails of sacrificed animals", note: "Real. A recognised public office, with training." },
  { w: "hypnagogic", pos: "adjective", def: "of the drowsy state just before falling asleep", note: "Real. That sudden falling sensation is a hypnagogic jerk." },
  { w: "imbroglio", pos: "noun", def: "a confused or embarrassing situation", note: "Real. Italian, from the same root as 'embroil'." },
  { w: "inglenook", pos: "noun", def: "a recess beside a large fireplace", note: "Real. 'Ingle' is an old word for the fire on a hearth." },
  { w: "interrobang", pos: "noun", def: "a punctuation mark combining a question mark and an exclamation point", note: "Real. Invented in 1962 by an advertising executive. It looks like this: &#8253;" },
  { w: "kerfuffle", pos: "noun", def: "a commotion or fuss", note: "Real. Scots, and still in daily use." },
  { w: "lacuna", pos: "noun", def: "a gap, especially a missing portion of a text", note: "Real. Latin for a pit or pool." },
  { w: "lambent", pos: "adjective", def: "glowing or flickering with a soft radiance", note: "Real. From Latin <em>lambere</em>, to lick — the flame licks the surface." },
  { w: "maunder", pos: "verb", def: "to talk ramblingly; to move about aimlessly", note: "Real. Not related to 'meander', despite the obvious suspicion." },
  { w: "mellifluous", pos: "adjective", def: "sweet and smooth to listen to", note: "Real. Latin <em>mel</em> (honey) + <em>fluere</em> (to flow)." },
  { w: "moiety", pos: "noun", def: "one of two parts into which something is divided", note: "Real, and still working in law and in chemistry." },
  { w: "nictitate", pos: "verb", def: "to blink", note: "Real. Many animals have a nictitating membrane — a third, transparent eyelid." },
  { w: "noctambulist", pos: "noun", def: "a sleepwalker", note: "Real. Latin <em>nox</em> (night) + <em>ambulare</em> (to walk)." },
  { w: "obstreperous", pos: "adjective", def: "noisy and difficult to control", note: "Real. Latin <em>ob-</em> (against) + <em>strepere</em> (to make a racket)." },
  { w: "omphaloskepsis", pos: "noun", def: "contemplation of one's own navel", note: "Real, and genuinely in the dictionary." },
  { w: "oneiric", pos: "adjective", def: "relating to dreams", note: "Real. Greek <em>oneiros</em>, dream." },
  { w: "palimpsest", pos: "noun", def: "a manuscript on which later writing covers earlier, erased writing", note: "Real. Parchment was costly, so scribes scraped it clean and started again." },
  { w: "panjandrum", pos: "noun", def: "a self-important official", note: "Real. Invented in 1755 inside a piece of nonsense written to test an actor's memory." },
  { w: "pettifogger", pos: "noun", def: "a lawyer who quibbles over trivia", note: "Real, and usefully insulting since the 1500s." },
  { w: "pilcrow", pos: "noun", def: "the paragraph mark, &para;", note: "Real. That symbol has a name, and this is it." },
  { w: "plangent", pos: "adjective", def: "loud and resonant, with a mournful tone", note: "Real. Usually said of bells, cellos and foghorns." },
  { w: "pleonasm", pos: "noun", def: "the use of more words than are needed", note: "Real. 'Free gift' and 'past history' are both pleonasms." },
  { w: "propinquity", pos: "noun", def: "nearness in place, time or relationship", note: "Real. From Latin <em>prope</em>, near." },
  { w: "ratiocination", pos: "noun", def: "the process of methodical reasoning", note: "Real. Poe used it for what his detective Dupin does." },
  { w: "recrudescence", pos: "noun", def: "the return of something unwelcome after a lull", note: "Real. From Latin for 'becoming raw again'." },
  { w: "salubrious", pos: "adjective", def: "health-giving; agreeable", note: "Real. From Latin <em>salus</em>, health." },
  { w: "saturnine", pos: "adjective", def: "gloomy or sullen in temperament", note: "Real. Astrology blamed it on being born under Saturn." },
  { w: "scintilla", pos: "noun", def: "a tiny trace or spark", note: "Real. Latin for spark, and the ancestor of 'scintillate'." },
  { w: "skeuomorph", pos: "noun", def: "a design feature that imitates something from an older version", note: "Real. The shutter click on a silent phone camera is one." },
  { w: "susurrus", pos: "noun", def: "a soft whispering or rustling sound", note: "Real, and the Latin imitates the sound itself." },
  { w: "thaumaturge", pos: "noun", def: "a worker of wonders or miracles", note: "Real. Greek <em>thauma</em>, marvel." },
  { w: "tmesis", pos: "noun", def: "the insertion of one word inside another", note: "Real. As in 'abso-blooming-lutely'." },
  { w: "troglodyte", pos: "noun", def: "a cave dweller; a person of unenlightened habits", note: "Real. Greek <em>trogle</em>, hole." },
  { w: "uxorious", pos: "adjective", def: "excessively devoted to one's wife", note: "Real. From Latin <em>uxor</em>, wife." },
  { w: "vespertine", pos: "adjective", def: "of or occurring in the evening", note: "Real, and the exact counterpart of 'matutinal'." },
  { w: "wamble", pos: "verb", def: "to move unsteadily; of the stomach, to feel queasy", note: "Real, and the ancestor of 'wobble'." },
  { w: "zoetrope", pos: "noun", def: "a spinning drum whose slits make still pictures appear to move", note: "Real. A Victorian toy, and an ancestor of cinema." },
  { w: "aglet", pos: "noun", def: "the small sheath at the end of a shoelace", note: "Real. It has a name, and this is it." },
  { w: "zarf", pos: "noun", def: "a holder for a cup that has no handle", note: "Real. Originally an ornamented metal one from the Ottoman world." },
  { w: "ferrule", pos: "noun", def: "the metal cap on the end of a stick or tool handle", note: "Real. Every walking stick and chisel has one." },
  { w: "philtrum", pos: "noun", def: "the vertical groove between the nose and the upper lip", note: "Real. Greek for 'love charm'." },
  { w: "tittle", pos: "noun", def: "the dot above a lowercase i or j", note: "Real. It is the tittle in 'not one jot or tittle'." },
  { w: "lunule", pos: "noun", def: "the pale crescent at the base of a fingernail", note: "Real. Latin for 'little moon'." },
  { w: "glabella", pos: "noun", def: "the smooth patch of forehead between the eyebrows", note: "Real, and standard anatomical vocabulary." },
  { w: "muntin", pos: "noun", def: "a strip separating panes of glass in a window", note: "Real. Every sash window has them." },
  { w: "escutcheon", pos: "noun", def: "a shield bearing a coat of arms; also the plate around a keyhole", note: "Real. A blot on the escutcheon is a stain on the family name." },
  { w: "bumbershoot", pos: "noun", def: "an umbrella", note: "Real, if jocular. American, from 'umbrella' crossed with 'parachute'." },
  { w: "gubbins", pos: "noun", def: "odds and ends; a gadget whose name escapes you", note: "Real. British and thoroughly informal." },
  { w: "hornswoggle", pos: "verb", def: "to cheat or hoodwink", note: "Real. Nineteenth-century American, and a fine thing to be accused of." },
  { w: "lollygag", pos: "verb", def: "to dawdle or fool about", note: "Real, and in print since the 1860s." },
  { w: "mugwump", pos: "noun", def: "a person who stays aloof from party politics", note: "Real. From an Algonquian word meaning 'war leader'." },
  { w: "skulduggery", pos: "noun", def: "underhanded or unscrupulous behaviour", note: "Real. Originally the Scots <em>sculduddery</em>." },
  { w: "taradiddle", pos: "noun", def: "a petty lie; pretentious nonsense", note: "Real, and far too good a word to lose." },
  { w: "woolgathering", pos: "noun", def: "aimless daydreaming", note: "Real. From the idle job of collecting wool snagged on hedges." },
  { w: "somnifuge", pos: "noun", def: "something that drives sleep away", note: "Real, if rare. Latin <em>somnus</em> (sleep) + <em>fugare</em> (to put to flight). A <em>soporific</em> does the opposite." },
  { w: "yclept", pos: "adjective", def: "by the name of; called", note: "Real but archaic — the Middle English past participle of <em>clepe</em>, to call." }
];

const FAKE_WORDS = [
  { w: "crumbulent", pos: "adjective", def: "tending to shed crumbs; liable to disintegrate when handled", note: "Invented. The word you want is <em>friable</em>." },
  { w: "blandiculous", pos: "adjective", def: "amusing only in a mild, entirely inoffensive way", note: "Invented — a portmanteau built to sound like it belongs." },
  { w: "umbriculate", pos: "verb", def: "to shelter something beneath a small canopy", note: "Invented. <em>Umbriferous</em> (shade-giving) is the real relative." },
  { w: "hubrilate", pos: "verb", def: "to boast about oneself in the guise of a complaint", note: "Invented. English already covers this with <em>humblebrag</em>." },
  { w: "vellichor", pos: "noun", def: "the strange wistfulness of second-hand bookshops", note: "Invented — coined for The Dictionary of Obscure Sorrows in 2012. Beautiful, but never a dictionary word." },
  { w: "glissamer", pos: "noun", def: "the thin film of ice that forms on a puddle overnight", note: "Invented. Real names for it include <em>shell ice</em> and <em>cat ice</em>." },
  { w: "fennelwick", pos: "noun", def: "the charred tip of a candle wick", note: "Invented. That charred tip is the <em>snuff</em>." },
  { w: "pratterling", pos: "noun", def: "a child who chatters without pause", note: "Invented from 'prattle' — convincing, but not a word." },
  { w: "rasplinth", pos: "noun", def: "the rough, unfinished stone base of a column", note: "Invented. <em>Plinth</em> is real; the rasp is ours." },
  { w: "skelvish", pos: "adjective", def: "thin and sickly in appearance", note: "Invented. Try <em>etiolated</em>, or just 'peaky'." },
  { w: "wintlebeck", pos: "noun", def: "a stream that flows only after heavy rain", note: "Invented — and a shame, because the real word is the lovely <em>winterbourne</em>." },
  { w: "thrumbleset", pos: "noun", def: "the low vibration felt through the floor of a moving train", note: "Invented, from 'thrum'." },
  { w: "norvient", pos: "adjective", def: "turned away from the prevailing wind", note: "Invented. Sailors just say <em>leeward</em>." },
  { w: "sprocketine", pos: "noun", def: "a single tooth on a gear wheel", note: "Invented. One tooth is a <em>cog</em>." },
  { w: "delphinate", pos: "verb", def: "to arch the back while entering the water in a dive", note: "Invented, from Latin <em>delphinus</em>, dolphin." },
  { w: "obelquin", pos: "noun", def: "a scribe's mark indicating a doubtful passage", note: "Invented. The genuine mark is an <em>obelus</em> (†)." },
  { w: "lorrimund", pos: "noun", def: "a hedge maze planted for walking meditation", note: "Invented. You're thinking of a <em>labyrinth</em>." },
  { w: "clatterfaust", pos: "noun", def: "a person who habitually slams cupboard doors", note: "Invented — German-ish suffix, entirely fictional." },
  { w: "gremulous", pos: "adjective", def: "faintly and persistently resentful", note: "Invented. You're half-remembering <em>querulous</em> and <em>tremulous</em>." },
  { w: "yaspernet", pos: "noun", def: "a fine mesh used for straining honey", note: "Invented. Beekeepers use a plain honey strainer." },
  { w: "brimsalop", pos: "noun", def: "the crust of salt left on the rim of a glass", note: "Invented." },
  { w: "tundlish", pos: "adjective", def: "slow-witted as a result of cold", note: "Invented." },
  { w: "quillevant", pos: "noun", def: "an ornamental feather worn in a hat", note: "Invented. Real options: <em>aigrette</em>, or a <em>panache</em>." },
  { w: "plinthery", pos: "noun", def: "decorative stonework running along the base of a wall", note: "Invented — the -ery is doing a lot of work." },
  { w: "serrivagant", pos: "adjective", def: "given to wandering among hills", note: "Invented. The rare-but-real one is <em>montivagant</em>." },
  { w: "cathomancy", pos: "noun", def: "divination by observing the behaviour of cats", note: "Invented — though divination by cat is real and is called <em>ailuromancy</em>." },
  { w: "flennick", pos: "noun", def: "a small blunt tool for prying open shellfish", note: "Invented. It's a <em>shucking knife</em>." },
  { w: "juvantine", pos: "adjective", def: "impulsive in the manner of the young", note: "Invented. <em>Juvenescent</em> is the real word." },
  { w: "gorbelt", pos: "noun", def: "the ring of cloud that forms around a mountain peak", note: "Invented. Meteorologists call it a <em>banner cloud</em>." },
  { w: "nixiate", pos: "verb", def: "to rub out a written mark", note: "Invented. <em>Expunge</em> or <em>efface</em> will do." },
  { w: "murkling", pos: "noun", def: "the dusk of a foggy evening", note: "Invented — it sounds like Old English, but it isn't." },
  { w: "quarnstile", pos: "noun", def: "a stone step set into a wall to allow crossing", note: "Invented. That is simply a <em>stile</em>." },
  { w: "bellamute", pos: "adjective", def: "silent but visibly angry", note: "Invented." },
  { w: "wemblish", pos: "adjective", def: "unsteady on the feet", note: "Invented — although <em>wamble</em>, to move unsteadily, is real." },
  { w: "hushpine", pos: "noun", def: "a sudden lull in conversation around a table", note: "Invented. The nearest real thing is the folk phrase 'an angel passing over'." },
  { w: "glaverwing", pos: "noun", def: "a moth that flies only at first light", note: "Invented — no such moth, no such word." },
  { w: "torpiculous", pos: "adjective", def: "sluggish and heavy after a large meal", note: "Invented. <em>Postprandial torpor</em> is the real (two-word) answer." },
  { w: "varnicle", pos: "noun", def: "the dimple in the base of a wine bottle", note: "Invented. That dimple is the <em>punt</em>." },
  { w: "veritude", pos: "noun", def: "the quality of sounding true without being true", note: "Invented — which is either ironic or fitting. <em>Verisimilitude</em> is the real one." },
  { w: "pluviscent", pos: "adjective", def: "smelling of rain that has not yet fallen", note: "Invented. The smell after rain does have a name though — <em>petrichor</em>." },
  { w: "tenebrile", pos: "adjective", def: "visible only in dim light", note: "Invented. <em>Tenebrous</em>, meaning dark or shadowy, is real." },
  { w: "fenestrine", pos: "adjective", def: "of light cast through a window", note: "Invented, from the real Latin <em>fenestra</em>, window." },
  { w: "verdurine", pos: "adjective", def: "of the green light beneath summer leaves", note: "Invented. <em>Verdure</em>, lush greenery, is real." },
  { w: "glinth", pos: "noun", def: "the sliver of light beneath a closed door", note: "Invented — no such word, and no such name for it." },
  { w: "flisken", pos: "noun", def: "the small gust of air let in by an opening door", note: "Invented." },
  { w: "wrindle", pos: "verb", def: "to crease cloth by gripping it", note: "Invented, from 'wrinkle' by way of nowhere." },
  { w: "tarnicle", pos: "noun", def: "the metal loop on a dog's collar", note: "Invented. That loop is just a D-ring." },
  { w: "brindlewick", pos: "noun", def: "the frayed end of a rope", note: "Invented. Sailors would say the rope has <em>fagged out</em>." },
  { w: "clabberwort", pos: "noun", def: "a weed that grows only on freshly turned soil", note: "Invented, though it sounds like something in a herbal." },
  { w: "mundicle", pos: "noun", def: "a small everyday object that has no name of its own", note: "Invented — and self-defeating, since it would then have one." },
  { w: "sobrement", pos: "noun", def: "the quiet that follows laughter", note: "Invented." },
  { w: "quillimet", pos: "noun", def: "the notch cut into the nib of a quill pen", note: "Invented. That cut is simply the <em>slit</em>." },
  { w: "hesperand", pos: "noun", def: "the last bird heard singing at dusk", note: "Invented, from Hesperus, the evening star." },
  { w: "morrowsome", pos: "adjective", def: "of a problem that looks smaller in the morning", note: "Invented." },
  { w: "gallimander", pos: "verb", def: "to wander off the point while telling a story", note: "Invented. <em>Maunder</em> already means roughly this, and is real." },
  { w: "crandle", pos: "verb", def: "to walk carefully over loose stones", note: "Invented." },
  { w: "rimswale", pos: "noun", def: "the ring a wet glass leaves on wood", note: "Invented. There is no accepted word for it, which is a shame." },
  { w: "drindle", pos: "verb", def: "to run slowly down a surface, of a liquid", note: "Invented — you are thinking of <em>trickle</em> or <em>dribble</em>." },
  { w: "blenkish", pos: "adjective", def: "pale from want of sleep", note: "Invented." },
  { w: "gorminate", pos: "verb", def: "to stare into the middle distance while thinking", note: "Invented — though <em>gormless</em>, its apparent relative, is real." },
  { w: "quaverling", pos: "noun", def: "a voice made unsteady by cold rather than nerves", note: "Invented." },
  { w: "snorrick", pos: "noun", def: "a knot pulled too tight to undo", note: "Invented." },
  { w: "umberwash", pos: "noun", def: "the brown light of a dust storm", note: "Invented, from the pigment umber." },
  { w: "murgle", pos: "verb", def: "to laugh with the mouth closed", note: "Invented." },
  { w: "glomber", pos: "verb", def: "to climb awkwardly, on hands and knees", note: "Invented — <em>clamber</em> is the real one." },
  { w: "plensive", pos: "adjective", def: "quietly regretful", note: "Invented. <em>Pensive</em> is real and close enough to fool most people." },
  { w: "cindrous", pos: "adjective", def: "resembling cold ash", note: "Invented. <em>Cinereous</em>, ash-grey, is real." },
  { w: "lumenette", pos: "noun", def: "the small light left burning for a child", note: "Invented. It is a night light." },
  { w: "gravelock", pos: "noun", def: "the sound of gravel underfoot", note: "Invented." },
  { w: "sallowick", pos: "noun", def: "the pale band of skin left by a removed ring", note: "Invented." },
  { w: "windleset", pos: "noun", def: "the pattern wind leaves on dry sand", note: "Invented. Geologists call those <em>ripple marks</em>." },
  { w: "yarnicle", pos: "noun", def: "a small tangle in a ball of wool", note: "Invented." },
  { w: "dawnling", pos: "noun", def: "the first bird call before sunrise", note: "Invented — the whole performance is the <em>dawn chorus</em>, which is real." },
  { w: "mirthling", pos: "noun", def: "a laugh that escapes at the wrong moment", note: "Invented." },
  { w: "scrimble", pos: "verb", def: "to write hurriedly and illegibly", note: "Invented. <em>Scribble</em> got there first." },
  { w: "felloquy", pos: "noun", def: "a conversation between two people who dislike each other", note: "Invented. <em>Colloquy</em>, a formal conversation, is real." },
  { w: "duskerly", pos: "adverb", def: "in the manner of failing light", note: "Invented." },
  { w: "glimmerwick", pos: "noun", def: "the last inch of a burning candle", note: "Invented. The stub is a <em>candle end</em>, unglamorously." },
  { w: "hushet", pos: "noun", def: "the small silence between two sounds", note: "Invented." },
  { w: "sundrift", pos: "noun", def: "a patch of sunlight that moves across a floor", note: "Invented." },
  { w: "tacitude", pos: "noun", def: "the habit of saying very little", note: "Invented. <em>Taciturnity</em> is the real word, and cats have it." },
  { w: "wintermark", pos: "noun", def: "the ring in a tree left by a hard winter", note: "Invented. Those are simply growth rings, read by <em>dendrochronology</em>." },
  { w: "zephyrine", pos: "adjective", def: "of a breeze too slight to move a leaf", note: "Invented. <em>Zephyr</em>, a gentle west wind, is real." },
  { w: "cloudle", pos: "verb", def: "to gather slowly, the way cloud does", note: "Invented." },
  { w: "frostling", pos: "noun", def: "the first frost of the year", note: "Invented." },
  { w: "lanterling", pos: "noun", def: "a moth circling a lamp", note: "Invented." },
  { w: "bellhollow", pos: "noun", def: "the pause after a bell stops ringing", note: "Invented." },
  { w: "rainwick", pos: "noun", def: "the drip from an eave after the rain has stopped", note: "Invented." },
  { w: "shimwrack", pos: "noun", def: "the heat haze that hangs above a road", note: "Invented. That shimmer is a <em>mirage</em>." },
  { w: "petrilune", pos: "noun", def: "the moon seen through mist", note: "Invented." },
  { w: "lattermorn", pos: "noun", def: "the hour of the morning after the rush is over", note: "Invented." },
  { w: "sundle", pos: "verb", def: "to divide something into unequal parts", note: "Invented." },
  { w: "gleamsome", pos: "adjective", def: "catching the light in a way that draws the eye", note: "Invented." }
];
