/* Lexicon Artist — the word bank.
 *
 * Every entry: { w: word, pos: part of speech, def: definition, real: true|false, note: shown after the guess }
 *
 * REAL entries are genuine English words with genuine definitions.
 * FAKE entries are inventions — plausible shapes, plausible meanings, no dictionary.
 * To add words, just append to either array. The game picks 5 real + 5 fake per round.
 */

const REAL_WORDS = [
  { w: "borborygmus", pos: "noun", def: "the rumbling noise made by gas moving through the intestines", note: "Real. From Greek <em>borborygmos</em> — the word is basically the sound." , ex: "The lecture hall fell silent just in time for everyone to hear the <em>borborygmus</em> from the back row." },
  { w: "petrichor", pos: "noun", def: "the pleasant earthy smell that follows rain falling on dry ground", note: "Real. Coined in 1964 by two Australian scientists, from Greek <em>petra</em> (stone) + <em>ichor</em> (the fluid in the veins of the gods)." , ex: "She opened the window after the storm and breathed in the <em>petrichor</em> rising off the hot pavement." },
  { w: "defenestration", pos: "noun", def: "the act of throwing someone or something out of a window", note: "Real. The Defenestrations of Prague (1419 and 1618) helped touch off two wars." , ex: "The <em>defenestration</em> of two royal officials in Prague in 1618 helped start a thirty-year war." },
  { w: "absquatulate", pos: "verb", def: "to leave abruptly; to make off with something", note: "Real. Nineteenth-century American mock-Latin — the frontier press loved inventing words that sounded classical." , ex: "He <em>absquatulated</em> with the petty cash before anyone thought to count it." },
  { w: "gallimaufry", pos: "noun", def: "a confused jumble or medley of things", note: "Real. It started life as a stew made of whatever was left in the kitchen." , ex: "The exhibition was a <em>gallimaufry</em> of half-finished sketches, ships' logs and stuffed birds." },
  { w: "mumpsimus", pos: "noun", def: "a stubborn adherence to a habit or notion even after it is shown to be wrong", note: "Real. From a priest who kept misreading the Latin <em>sumpsimus</em> as <em>mumpsimus</em> and refused to be corrected." , ex: "Correcting his grammar was hopeless; the man was a <em>mumpsimus</em> about the split infinitive." },
  { w: "sesquipedalian", pos: "adjective", def: "(of a word) very long; given to using long words", note: "Real, and self-demonstrating. Literally 'a foot and a half long', from Horace." , ex: "Her <em>sesquipedalian</em> prose sent readers to the dictionary twice a paragraph." },
  { w: "tergiversate", pos: "verb", def: "to make conflicting or evasive statements; to switch loyalties", note: "Real. Latin <em>tergum</em> (back) + <em>versare</em> (to turn) — to turn your back." , ex: "The minister <em>tergiversated</em> for a week before admitting he had changed sides." },
  { w: "ultracrepidarian", pos: "noun", def: "a person who gives opinions on matters beyond their knowledge", note: "Real. From a cobbler who criticised a painting above the shoe line: <em>ne sutor ultra crepidam</em>." , ex: "Every comment section has its <em>ultracrepidarian</em>, explaining epidemiology to epidemiologists." },
  { w: "widdershins", pos: "adverb", def: "in a direction contrary to the sun's course; counterclockwise", note: "Real. Scots, and long thought to be unlucky." , ex: "Superstitious sailors never walked <em>widdershins</em> around the mast." },
  { w: "zugzwang", pos: "noun", def: "a position in which any move a player can make will worsen it", note: "Real — a chess term borrowed whole from German: 'compulsion to move'." , ex: "Two moves from the end he was in <em>zugzwang</em>: every legal move lost a piece." },
  { w: "quidnunc", pos: "noun", def: "an inquisitive, gossiping person; a busybody", note: "Real. From the Latin <em>quid nunc?</em> — 'what now?'" , ex: "The village <em>quidnunc</em> knew about the engagement before the couple did." },
  { w: "rebarbative", pos: "adjective", def: "unattractive and objectionable; repellent", note: "Real. From French — literally to stand beard-to-beard with someone." , ex: "His manner was so <em>rebarbative</em> that even the dog left the room." },
  { w: "snollygoster", pos: "noun", def: "a shrewd, unprincipled person, especially a politician", note: "Real. Nineteenth-century American, and overdue for a comeback." , ex: "The editorial called the new senator a <em>snollygoster</em> with a talent for the microphone." },
  { w: "velleity", pos: "noun", def: "a wish or inclination too slight to lead to any action", note: "Real. From Latin <em>velle</em>, to wish. The word for wanting to go to the gym." , ex: "Learning the cello remained a <em>velleity</em>; the instrument stayed in its case for years." },
  { w: "floccinaucinihilipilification", pos: "noun", def: "the act of estimating something as worthless", note: "Real, if barely used — it was assembled in the 18th century out of four Latin words all meaning 'trifle'." , ex: "His <em>floccinaucinihilipilification</em> of modern art was as tiresome as the word itself." },
  { w: "cachinnate", pos: "verb", def: "to laugh loudly or immoderately", note: "Real. Latin <em>cachinnare</em>, to guffaw." , ex: "The audience <em>cachinnated</em> so loudly that the actors had to wait to go on." },
  { w: "brontide", pos: "noun", def: "a low muffled rumbling like distant thunder", note: "Real. From Greek <em>bronte</em>, thunder — the same root as the dinosaur." , ex: "A low <em>brontide</em> rolled across the valley long before the first clouds appeared." },
  { w: "limerence", pos: "noun", def: "the state of being obsessively infatuated with another person", note: "Real. Coined by the psychologist Dorothy Tennov in the 1970s and now in wide use." , ex: "Six months of <em>limerence</em> ended the moment she heard him chew." },
  { w: "deipnosophist", pos: "noun", def: "a person skilled in table talk", note: "Real. From Athenaeus's third-century work <em>The Deipnosophists</em> — dinner guests who talk beautifully." , ex: "A born <em>deipnosophist</em>, he could keep eight strangers talking through four courses." },
  { w: "mondegreen", pos: "noun", def: "a misheard word or phrase, especially in a song lyric", note: "Real. Coined in 1954 from 'laid him on the green' misheard as 'Lady Mondegreen'." , ex: "'Sweet dreams are made of cheese' is the most cheerful <em>mondegreen</em> in pop music." },
  { w: "callipygian", pos: "adjective", def: "having shapely buttocks", note: "Real. Greek <em>kallos</em> (beauty) + <em>pyge</em>. There is a famous statue named for it." , ex: "The museum's <em>callipygian</em> statue drew more visitors than the entire Roman wing." },
  { w: "bibulous", pos: "adjective", def: "excessively fond of drinking alcohol; also, absorbent", note: "Real. Latin <em>bibere</em>, to drink — the same root as 'imbibe'." , ex: "After a <em>bibulous</em> evening at the club, he took the long way home." },
  { w: "jentacular", pos: "adjective", def: "relating to breakfast", note: "Real, if archaic. From Latin <em>jentaculum</em>, the first meal of the day." , ex: "He defended his <em>jentacular</em> habits: two eggs, black coffee, and no conversation." },
  { w: "kakistocracy", pos: "noun", def: "government by the worst or least qualified people", note: "Real. Greek <em>kakistos</em>, worst. In use since the 1600s." , ex: "The pamphlet argued that the republic had slid into outright <em>kakistocracy</em>." },
  { w: "matutinal", pos: "adjective", def: "of or occurring in the morning", note: "Real. The opposite number is 'vespertine', of the evening." , ex: "Her <em>matutinal</em> routine — swim, coffee, newspaper — did not vary in thirty years." },
  { w: "obnubilate", pos: "verb", def: "to darken, dim, or obscure", note: "Real. Latin <em>nubes</em>, cloud — literally to cloud over." , ex: "Smoke from the fires <em>obnubilated</em> the sun for three days." },
  { w: "pandiculation", pos: "noun", def: "the stretching and yawning that accompanies waking", note: "Real, and used in medicine. Cats are experts." , ex: "The cat's morning <em>pandiculation</em> took longer than breakfast." },
  { w: "quockerwodger", pos: "noun", def: "a wooden puppet on strings; hence a politician controlled by someone else", note: "Real Victorian slang. Yes, really." , ex: "The cartoonist drew the governor as a <em>quockerwodger</em>, strings running up to the lobbyists." },
  { w: "rodomontade", pos: "noun", def: "boastful or inflated talk", note: "Real. From Rodomonte, a swaggering braggart in Italian romance." , ex: "The speech was pure <em>rodomontade</em>: twenty minutes of promises and not one number." },
  { w: "tatterdemalion", pos: "noun", def: "a person in ragged clothing", note: "Real, first recorded in the early 1600s." , ex: "A <em>tatterdemalion</em> band of survivors reached the fort at dawn." },
  { w: "usufruct", pos: "noun", def: "the legal right to use and enjoy the profits of property belonging to another", note: "Real. Straight out of Roman law and still live in modern civil codes." , ex: "The will left her the <em>usufruct</em> of the orchard, though the land itself passed to her nephew." },
  { w: "yaffle", pos: "noun", def: "a green woodpecker", note: "Real British dialect, imitating the bird's laughing call." , ex: "A <em>yaffle</em> laughed somewhere in the beeches and then went quiet." },
  { w: "agelast", pos: "noun", def: "a person who never laughs", note: "Real. Greek <em>a-</em> (not) + <em>gelan</em> (to laugh)." , ex: "He was a complete <em>agelast</em> — twelve years of friendship, and nobody had seen him smile." },
  { w: "bloviate", pos: "verb", def: "to speak or write at length in a pompous, empty way", note: "Real American coinage, forever associated with President Warren G. Harding." , ex: "Given a microphone, he would <em>bloviate</em> about the deficit until the room emptied." },
  { w: "hebetude", pos: "noun", def: "dullness of mind; mental lethargy", note: "Real. Latin <em>hebes</em>, blunt." , ex: "August heat brought a general <em>hebetude</em> to the office; nothing was decided until September." },
  { w: "incunabula", pos: "noun", def: "books printed before 1501; by extension, the earliest stages of something", note: "Real. Latin for 'swaddling clothes' — the infancy of printing." , ex: "The library's <em>incunabula</em> are kept behind glass, in gloves-only conditions." },
  { w: "fuliginous", pos: "adjective", def: "sooty; of the colour of soot", note: "Real. Latin <em>fuligo</em>, soot." , ex: "A <em>fuliginous</em> haze hung over the ironworks even on still days." },
  { w: "crepuscular", pos: "adjective", def: "of or resembling twilight; (of animals) active at dawn and dusk", note: "Real. Deer, rabbits and mosquitoes are all crepuscular." , ex: "Deer are <em>crepuscular</em>, which is why they meet so many cars at dusk." },
  { w: "lachrymose", pos: "adjective", def: "tearful, or inclined to produce tears", note: "Real. Latin <em>lacrima</em>, tear." , ex: "Three glasses in, he turned <em>lachrymose</em> about a dog he had owned in 1994." },
  { w: "anserine", pos: "adjective", def: "of or resembling a goose; hence, silly", note: "Real. Latin <em>anser</em>, goose — the bird equivalent of 'bovine'." , ex: "She dismissed the whole plan with an <em>anserine</em> giggle and no argument at all." },
  { w: "scrimshaw", pos: "noun", def: "carved or engraved work in whalebone or ivory, made by sailors", note: "Real. A whaling-ship craft from the 1800s." , ex: "The captain's <em>scrimshaw</em> — a whale's tooth carved with a full-rigged ship — sold for thousands." },
  { w: "epizeuxis", pos: "noun", def: "the immediate repetition of a word for emphasis", note: "Real — a rhetorical figure. 'Never, never, never give up.'" , ex: "Churchill's 'never, never, never' is <em>epizeuxis</em> doing the work of a paragraph." },
  { w: "nyctalopia", pos: "noun", def: "night blindness; poor vision in low light", note: "Real, and a genuine medical diagnosis, often from vitamin A deficiency." , ex: "His <em>nyctalopia</em> made driving after sunset out of the question." },
  { w: "zoanthropy", pos: "noun", def: "the delusion that one has become an animal", note: "Real, an old psychiatric term. Lycanthropy is the wolf-specific version." , ex: "The old case notes described a patient with <em>zoanthropy</em> who was certain he was a wolf." },
  { w: "abecedarian", pos: "noun", def: "a person learning the alphabet; a beginner in any subject", note: "Real. Named for the first four letters — A, B, C, D." , ex: "At forty he was a cheerful <em>abecedarian</em> in Japanese, still proud of his hiragana." },
  { w: "aeolian", pos: "adjective", def: "produced or carried by the wind", note: "Real. From Aeolus, keeper of the winds. An aeolian harp is played by the breeze alone." , ex: "The <em>aeolian</em> ridges of the dune shifted a few feet every winter." },
  { w: "apotropaic", pos: "adjective", def: "intended to ward off evil", note: "Real. Horseshoes over doorways and gargoyles on churches are both apotropaic." , ex: "The blue beads above the doorway were <em>apotropaic</em>, hung there to turn away the evil eye." },
  { w: "autochthonous", pos: "adjective", def: "native to the place where it is found", note: "Real. Greek <em>autos</em> (self) + <em>chthon</em> (earth) — sprung from the ground itself." , ex: "The valley's <em>autochthonous</em> oaks predate every wall and road around them." },
  { w: "bezoar", pos: "noun", def: "a hard mass of undigested material found in the stomach", note: "Real. For centuries it was believed to be an antidote to every poison." , ex: "A Renaissance prince would pay a fortune for a <em>bezoar</em>, believing it neutralised any poison." },
  { w: "blatherskite", pos: "noun", def: "a person who talks at great length without making sense", note: "Real. Scots by birth, and popular in America since the Revolution." , ex: "The meeting was hijacked by a <em>blatherskite</em> from accounts with forty slides." },
  { w: "brumal", pos: "adjective", def: "belonging to or occurring in winter", note: "Real. From Latin <em>bruma</em>, the winter solstice." , ex: "The house takes on a <em>brumal</em> silence once the last visitors leave in November." },
  { w: "cacoethes", pos: "noun", def: "an irresistible urge to do something inadvisable", note: "Real. Greek for a bad habit. <em>Cacoethes scribendi</em> is the incurable itch to write." , ex: "She had a <em>cacoethes</em> for buying houseplants she had no light to keep alive." },
  { w: "caliginous", pos: "adjective", def: "misty, dim, obscure", note: "Real. From Latin <em>caligo</em>, mist." , ex: "The path vanished into a <em>caliginous</em> stretch of woodland." },
  { w: "chiaroscuro", pos: "noun", def: "the arrangement of light and shade in a picture", note: "Real. Italian for light-dark. Caravaggio built a career on it." , ex: "The portrait's <em>chiaroscuro</em> leaves half the sitter's face in darkness." },
  { w: "clerisy", pos: "noun", def: "the learned class taken as a whole", note: "Real. Coined by Samuel Taylor Coleridge, who felt England needed one." , ex: "He wrote for the <em>clerisy</em> and was baffled when the book sold twelve copies." },
  { w: "collywobbles", pos: "noun", def: "stomach pain, or a feeling of nervousness", note: "Real. Probably a playful mangling of <em>cholera morbus</em>." , ex: "Waiting in the wings gave her the <em>collywobbles</em> every single night." },
  { w: "concinnity", pos: "noun", def: "elegant harmony in the way parts are arranged", note: "Real. A favourite term of Cicero's admirers." , ex: "There is a <em>concinnity</em> to her sentences that survives translation." },
  { w: "crapulous", pos: "adjective", def: "suffering the effects of too much drink", note: "Real. From Latin <em>crapula</em>, intoxication." , ex: "He arrived <em>crapulous</em> and unshaven, an hour after the ceremony began." },
  { w: "desuetude", pos: "noun", def: "a state of disuse", note: "Real. Laws nobody bothers to enforce are said to fall into desuetude." , ex: "The duelling statutes fell into <em>desuetude</em> long before anyone repealed them." },
  { w: "dolorous", pos: "adjective", def: "feeling or expressing great sorrow", note: "Real. From Latin <em>dolor</em>, pain — the same root that gives us <em>condolences</em>.", ex: "A <em>dolorous</em> horn sounded twice from the far side of the lake." },
  { w: "logorrhea", pos: "noun", def: "excessive and often incoherent talkativeness", note: "Real, and a genuine clinical term. Greek <em>logos</em> (word) + <em>rhein</em> (to flow).", ex: "The witness's <em>logorrhea</em> filled ninety pages of transcript and settled nothing." },
  { w: "eldritch", pos: "adjective", def: "weird, eerie, unearthly", note: "Real. Scots, and the reason so much horror fiction sounds Scottish." , ex: "An <em>eldritch</em> light moved across the marsh, and nobody volunteered to investigate." },
  { w: "embrocation", pos: "noun", def: "a liquid rubbed into the body to relieve aches", note: "Real. Standard issue in every nineteenth-century medicine cabinet." , ex: "The trainer worked <em>embrocation</em> into the horse's shoulder before the race." },
  { w: "farrago", pos: "noun", def: "a confused mixture", note: "Real. Latin for mixed fodder fed to cattle." , ex: "The report was a <em>farrago</em> of rumour, guesswork and one genuine fact." },
  { w: "fissiparous", pos: "adjective", def: "inclined to split into factions", note: "Real. Biology got it first, for cells that reproduce by dividing." , ex: "The party proved <em>fissiparous</em>, splitting into three factions within a year." },
  { w: "flibbertigibbet", pos: "noun", def: "a frivolous, flighty person", note: "Real. It began as the name of a devil in <em>King Lear</em>." , ex: "Her aunt dismissed the new fiancée as a <em>flibbertigibbet</em> with no head for money." },
  { w: "frangible", pos: "adjective", def: "easily broken; fragile", note: "Real. Same root as 'fracture'." , ex: "The bones of a bird are <em>frangible</em>, built for lightness rather than strength." },
  { w: "gasconade", pos: "noun", def: "extravagant boasting", note: "Real. From Gascony, whose people had a reputation for exactly that." , ex: "His account of the hunt was mostly <em>gasconade</em>; the deer had escaped." },
  { w: "gormless", pos: "adjective", def: "lacking sense or initiative", note: "Real. From an old northern English word, <em>gaum</em>, meaning understanding." , ex: "He stood there <em>gormless</em>, holding a bouquet at the wrong address." },
  { w: "haruspex", pos: "noun", def: "a Roman priest who read omens in the entrails of sacrificed animals", note: "Real. A recognised public office, with training." , ex: "Before the battle, the <em>haruspex</em> examined the liver and pronounced the omens good." },
  { w: "hypnagogic", pos: "adjective", def: "of the drowsy state just before falling asleep", note: "Real. That sudden falling sensation is a hypnagogic jerk." , ex: "In that <em>hypnagogic</em> drift before sleep she often heard her name called." },
  { w: "imbroglio", pos: "noun", def: "a confused or embarrassing situation", note: "Real. Italian, from the same root as 'embroil'." , ex: "The entire <em>imbroglio</em> began with one misdirected email." },
  { w: "inglenook", pos: "noun", def: "a recess beside a large fireplace", note: "Real. 'Ingle' is an old word for the fire on a hearth." , ex: "They took the corner seats in the <em>inglenook</em>, closest to the fire." },
  { w: "interrobang", pos: "noun", def: "a punctuation mark combining a question mark and an exclamation point", note: "Real. Invented in 1962 by an advertising executive. It looks like this: &#8253;" , ex: "Nothing else punctuates 'you did what' quite like an <em>interrobang</em>." },
  { w: "kerfuffle", pos: "noun", def: "a commotion or fuss", note: "Real. Scots, and still in daily use." , ex: "There was a brief <em>kerfuffle</em> at the door over an unpaid bar tab." },
  { w: "lacuna", pos: "noun", def: "a gap, especially a missing portion of a text", note: "Real. Latin for a pit or pool." , ex: "The manuscript has a <em>lacuna</em> where three lines were lost to damp." },
  { w: "lambent", pos: "adjective", def: "glowing or flickering with a soft radiance", note: "Real. From Latin <em>lambere</em>, to lick — the flame licks the surface." , ex: "A <em>lambent</em> glow came off the coals long after the flames died." },
  { w: "maunder", pos: "verb", def: "to talk ramblingly; to move about aimlessly", note: "Real. Not related to 'meander', despite the obvious suspicion." , ex: "He would <em>maunder</em> about the war for hours without ever reaching a point." },
  { w: "mellifluous", pos: "adjective", def: "sweet and smooth to listen to", note: "Real. Latin <em>mel</em> (honey) + <em>fluere</em> (to flow)." , ex: "Her <em>mellifluous</em> reading voice sold more audiobooks than the author's name did." },
  { w: "moiety", pos: "noun", def: "one of two parts into which something is divided", note: "Real, and still working in law and in chemistry." , ex: "Each <em>moiety</em> of the estate went to a different branch of the family." },
  { w: "nictitate", pos: "verb", def: "to blink", note: "Real. Many animals have a nictitating membrane — a third, transparent eyelid." , ex: "The hawk <em>nictitated</em> once, a pale membrane sweeping the eye clean." },
  { w: "noctambulist", pos: "noun", def: "a sleepwalker", note: "Real. Latin <em>nox</em> (night) + <em>ambulare</em> (to walk)." , ex: "As a child he was a <em>noctambulist</em>, and his parents put a bell on the front door." },
  { w: "obstreperous", pos: "adjective", def: "noisy and difficult to control", note: "Real. Latin <em>ob-</em> (against) + <em>strepere</em> (to make a racket)." , ex: "The class turned <em>obstreperous</em> the moment the substitute teacher appeared." },
  { w: "omphaloskepsis", pos: "noun", def: "contemplation of one's own navel", note: "Real, and genuinely in the dictionary." , ex: "The retreat was billed as reflection but amounted to three days of <em>omphaloskepsis</em>." },
  { w: "oneiric", pos: "adjective", def: "relating to dreams", note: "Real. Greek <em>oneiros</em>, dream." , ex: "The film has an <em>oneiric</em> logic — corridors that lead back into the same room." },
  { w: "palimpsest", pos: "noun", def: "a manuscript on which later writing covers earlier, erased writing", note: "Real. Parchment was costly, so scribes scraped it clean and started again." , ex: "The city is a <em>palimpsest</em>: Roman walls under Norman streets under Victorian brick." },
  { w: "panjandrum", pos: "noun", def: "a self-important official", note: "Real. Invented in 1755 inside a piece of nonsense written to test an actor's memory." , ex: "Some <em>panjandrum</em> from head office arrived to explain our own jobs to us." },
  { w: "pettifogger", pos: "noun", def: "a lawyer who quibbles over trivia", note: "Real, and usefully insulting since the 1500s." , ex: "The case was dragged out for years by a <em>pettifogger</em> arguing over commas." },
  { w: "pilcrow", pos: "noun", def: "the paragraph mark, &para;", note: "Real. That symbol has a name, and this is it." , ex: "Turn on formatting marks and every paragraph sprouts a <em>pilcrow</em>." },
  { w: "plangent", pos: "adjective", def: "loud and resonant, with a mournful tone", note: "Real. Usually said of bells, cellos and foghorns." , ex: "A <em>plangent</em> cello line carried the whole second act." },
  { w: "pleonasm", pos: "noun", def: "the use of more words than are needed", note: "Real. 'Free gift' and 'past history' are both pleonasms." , ex: "'Advance planning' is a <em>pleonasm</em>; all planning is done in advance." },
  { w: "propinquity", pos: "noun", def: "nearness in place, time or relationship", note: "Real. From Latin <em>prope</em>, near." , ex: "Their friendship began in mere <em>propinquity</em> — adjacent desks, nothing more." },
  { w: "ratiocination", pos: "noun", def: "the process of methodical reasoning", note: "Real. Poe used it for what his detective Dupin does." , ex: "Holmes's <em>ratiocination</em> turns a splash of mud into a confession." },
  { w: "recrudescence", pos: "noun", def: "the return of something unwelcome after a lull", note: "Real. From Latin for 'becoming raw again'." , ex: "Autumn brought a <em>recrudescence</em> of the cough he thought he had beaten." },
  { w: "salubrious", pos: "adjective", def: "health-giving; agreeable", note: "Real. From Latin <em>salus</em>, health." , ex: "The doctor prescribed a month in a more <em>salubrious</em> climate." },
  { w: "saturnine", pos: "adjective", def: "gloomy or sullen in temperament", note: "Real. Astrology blamed it on being born under Saturn." , ex: "Her <em>saturnine</em> brother sat through the whole wedding without lifting his eyes." },
  { w: "scintilla", pos: "noun", def: "a tiny trace or spark", note: "Real. Latin for spark, and the ancestor of 'scintillate'." , ex: "There was not a <em>scintilla</em> of evidence linking him to the theft." },
  { w: "skeuomorph", pos: "noun", def: "a design feature that imitates something from an older version", note: "Real. The shutter click on a silent phone camera is one." , ex: "The little floppy disk on the save button is a <em>skeuomorph</em> nobody under twenty recognises." },
  { w: "susurrus", pos: "noun", def: "a soft whispering or rustling sound", note: "Real, and the Latin imitates the sound itself." , ex: "A <em>susurrus</em> of paper ran through the hall as everyone turned the page at once." },
  { w: "thaumaturge", pos: "noun", def: "a worker of wonders or miracles", note: "Real. Greek <em>thauma</em>, marvel." , ex: "The village treated the new doctor as a <em>thaumaturge</em> rather than a scientist." },
  { w: "tmesis", pos: "noun", def: "the insertion of one word inside another", note: "Real. As in 'abso-blooming-lutely'." , ex: "'Abso-blooming-lutely' is <em>tmesis</em>, and Eliza Doolittle's finest hour of grammar." },
  { w: "troglodyte", pos: "noun", def: "a cave dweller; a person of unenlightened habits", note: "Real. Greek <em>trogle</em>, hole." , ex: "He called himself a <em>troglodyte</em> — three months underground, mapping the cave system." },
  { w: "uxorious", pos: "adjective", def: "excessively devoted to one's wife", note: "Real. From Latin <em>uxor</em>, wife." , ex: "So <em>uxorious</em> was the old man that he refused every invitation his wife declined." },
  { w: "vespertine", pos: "adjective", def: "of or occurring in the evening", note: "Real, and the exact counterpart of 'matutinal'." , ex: "The <em>vespertine</em> chorus of bats begins about twenty minutes after sunset." },
  { w: "wamble", pos: "verb", def: "to move unsteadily; of the stomach, to feel queasy", note: "Real, and the ancestor of 'wobble'." , ex: "The ferry pitched hard, and his stomach began to <em>wamble</em>." },
  { w: "zoetrope", pos: "noun", def: "a spinning drum whose slits make still pictures appear to move", note: "Real. A Victorian toy, and an ancestor of cinema." , ex: "A <em>zoetrope</em> on the nursery shelf turned twelve drawings into a galloping horse." },
  { w: "aglet", pos: "noun", def: "the small sheath at the end of a shoelace", note: "Real. It has a name, and this is it." , ex: "The <em>aglet</em> had come off, and threading the lace became a two-minute job." },
  { w: "zarf", pos: "noun", def: "a holder for a cup that has no handle", note: "Real. Originally an ornamented metal one from the Ottoman world." , ex: "The coffee arrived in a brass <em>zarf</em>, the glass inside far too hot to hold." },
  { w: "ferrule", pos: "noun", def: "the metal cap on the end of a stick or tool handle", note: "Real. Every walking stick and chisel has one." , ex: "The walking stick's rubber <em>ferrule</em> had worn through to the metal." },
  { w: "philtrum", pos: "noun", def: "the vertical groove between the nose and the upper lip", note: "Real. Greek for 'love charm'." , ex: "A drop of rain sat in the <em>philtrum</em> just above his lip." },
  { w: "tittle", pos: "noun", def: "the dot above a lowercase i or j", note: "Real. It is the tittle in 'not one jot or tittle'." , ex: "Handwriting analysts make much of where a writer puts the <em>tittle</em> over an i." },
  { w: "lunule", pos: "noun", def: "the pale crescent at the base of a fingernail", note: "Real. Latin for 'little moon'." , ex: "The <em>lunule</em> on her thumb was the only one still visible." },
  { w: "glabella", pos: "noun", def: "the smooth patch of forehead between the eyebrows", note: "Real, and standard anatomical vocabulary." , ex: "He pressed two fingers to his <em>glabella</em>, willing the headache away." },
  { w: "muntin", pos: "noun", def: "a strip separating panes of glass in a window", note: "Real. Every sash window has them." , ex: "Each <em>muntin</em> had to be repainted by hand, twelve panes to a window." },
  { w: "escutcheon", pos: "noun", def: "a shield bearing a coat of arms; also the plate around a keyhole", note: "Real. A blot on the escutcheon is a stain on the family name." , ex: "The brass <em>escutcheon</em> around the keyhole was worn bright by a century of use." },
  { w: "bumbershoot", pos: "noun", def: "an umbrella", note: "Real, if jocular. American, from 'umbrella' crossed with 'parachute'." , ex: "He set off into the drizzle under an enormous striped <em>bumbershoot</em>." },
  { w: "gubbins", pos: "noun", def: "odds and ends; a gadget whose name escapes you", note: "Real. British and thoroughly informal." , ex: "The drawer was full of <em>gubbins</em> — cables, adaptors and keys to nothing." },
  { w: "hornswoggle", pos: "verb", def: "to cheat or hoodwink", note: "Real. Nineteenth-century American, and a fine thing to be accused of." , ex: "The dealer tried to <em>hornswoggle</em> him over the mileage." },
  { w: "lollygag", pos: "verb", def: "to dawdle or fool about", note: "Real, and in print since the 1860s." , ex: "Stop <em>lollygagging</em> by the vending machine; the train leaves in four minutes." },
  { w: "mugwump", pos: "noun", def: "a person who stays aloof from party politics", note: "Real. From an Algonquian word meaning 'war leader'." , ex: "He remained a <em>mugwump</em> through three elections, refusing to endorse anyone." },
  { w: "skulduggery", pos: "noun", def: "underhanded or unscrupulous behaviour", note: "Real. Originally the Scots <em>sculduddery</em>." , ex: "The audit uncovered genuine <em>skulduggery</em> in the procurement office." },
  { w: "taradiddle", pos: "noun", def: "a petty lie; pretentious nonsense", note: "Real, and far too good a word to lose." , ex: "The excuse was a transparent <em>taradiddle</em> about a flat tyre." },
  { w: "woolgathering", pos: "noun", def: "aimless daydreaming", note: "Real. From the idle job of collecting wool snagged on hedges." , ex: "An afternoon of <em>woolgathering</em> at the window produced no work at all." },
  { w: "somnifuge", pos: "noun", def: "something that drives sleep away", note: "Real, if rare. Latin <em>somnus</em> (sleep) + <em>fugare</em> (to put to flight). A <em>soporific</em> does the opposite." , ex: "Strong coffee after nine is a reliable <em>somnifuge</em>." },
  { w: "yclept", pos: "adjective", def: "by the name of; called", note: "Real but archaic — the Middle English past participle of <em>clepe</em>, to call." , ex: "A knight <em>yclept</em> Gareth arrives in the third chapter and immediately loses his horse." }
];

const FAKE_WORDS = [
  { w: "crumbulent", pos: "adjective", def: "tending to shed crumbs; liable to disintegrate when handled", note: "Invented. The word you want is <em>friable</em>." },
  { w: "blandiculous", pos: "adjective", def: "amusing only in a mild, entirely inoffensive way", note: "Invented — a portmanteau built to sound like it belongs." },
  { w: "umbriculate", pos: "verb", def: "to shelter something beneath a small canopy", note: "Invented. <em>Umbriferous</em> (shade-giving) is the real relative." },
  { w: "hubrilate", pos: "verb", def: "to boast about oneself in the guise of a complaint", note: "Invented. English already covers this with <em>humblebrag</em>." },
  { w: "vellichor", pos: "noun", def: "the strange wistfulness of second-hand bookshops", note: "Invented — coined for The Dictionary of Obscure Sorrows in 2012. Beautiful, but never a dictionary word." },
  { w: "glissamer", pos: "noun", def: "the thin film of ice that forms on a puddle overnight", note: "Invented. Real names for it include <em>shell ice</em> and <em>cat ice</em>." },
  { w: "fennelwick", pos: "noun", def: "the charred tip of a candle wick", note: "Invented. That charred tip is the <em>snuff</em>." },
  { w: "pratterling", pos: "noun", def: "a child who chatters without pause", note: "Invented from 'prattle' — convincing, but not a word." },
  { w: "rasplinth", pos: "noun", def: "the rough, unfinished stone base of a column", note: "Invented. <em>Plinth</em> is real; the rasp is ours." },
  { w: "skelvish", pos: "adjective", def: "thin and sickly in appearance", note: "Invented. Try <em>etiolated</em>, or just 'peaky'." },
  { w: "wintlebeck", pos: "noun", def: "a stream that flows only after heavy rain", note: "Invented — and a shame, because the real word is the lovely <em>winterbourne</em>." },
  { w: "thrumbleset", pos: "noun", def: "the low vibration felt through the floor of a moving train", note: "Invented, from 'thrum'." },
  { w: "norvient", pos: "adjective", def: "turned away from the prevailing wind", note: "Invented. Sailors just say <em>leeward</em>." },
  { w: "sprocketine", pos: "noun", def: "a single tooth on a gear wheel", note: "Invented. One tooth is a <em>cog</em>." },
  { w: "delphinate", pos: "verb", def: "to arch the back while entering the water in a dive", note: "Invented, from Latin <em>delphinus</em>, dolphin." },
  { w: "obelquin", pos: "noun", def: "a scribe's mark indicating a doubtful passage", note: "Invented. The genuine mark is an <em>obelus</em> (†)." },
  { w: "lorrimund", pos: "noun", def: "a hedge maze planted for walking meditation", note: "Invented. You're thinking of a <em>labyrinth</em>." },
  { w: "clatterfaust", pos: "noun", def: "a person who habitually slams cupboard doors", note: "Invented — German-ish suffix, entirely fictional." },
  { w: "gremulous", pos: "adjective", def: "faintly and persistently resentful", note: "Invented. You're half-remembering <em>querulous</em> and <em>tremulous</em>." },
  { w: "yaspernet", pos: "noun", def: "a fine mesh used for straining honey", note: "Invented. Beekeepers use a plain honey strainer." },
  { w: "brimsalop", pos: "noun", def: "the crust of salt left on the rim of a glass", note: "Invented." },
  { w: "tundlish", pos: "adjective", def: "slow-witted as a result of cold", note: "Invented." },
  { w: "quillevant", pos: "noun", def: "an ornamental feather worn in a hat", note: "Invented. Real options: <em>aigrette</em>, or a <em>panache</em>." },
  { w: "plinthery", pos: "noun", def: "decorative stonework running along the base of a wall", note: "Invented — the -ery is doing a lot of work." },
  { w: "serrivagant", pos: "adjective", def: "given to wandering among hills", note: "Invented. The rare-but-real one is <em>montivagant</em>." },
  { w: "cathomancy", pos: "noun", def: "divination by observing the behaviour of cats", note: "Invented — though divination by cat is real and is called <em>ailuromancy</em>." },
  { w: "flennick", pos: "noun", def: "a small blunt tool for prying open shellfish", note: "Invented. It's a <em>shucking knife</em>." },
  { w: "juvantine", pos: "adjective", def: "impulsive in the manner of the young", note: "Invented. <em>Juvenescent</em> is the real word." },
  { w: "gorbelt", pos: "noun", def: "the ring of cloud that forms around a mountain peak", note: "Invented. Meteorologists call it a <em>banner cloud</em>." },
  { w: "nixiate", pos: "verb", def: "to rub out a written mark", note: "Invented. <em>Expunge</em> or <em>efface</em> will do." },
  { w: "murkling", pos: "noun", def: "the dusk of a foggy evening", note: "Invented — it sounds like Old English, but it isn't." },
  { w: "quarnstile", pos: "noun", def: "a stone step set into a wall to allow crossing", note: "Invented. That is simply a <em>stile</em>." },
  { w: "bellamute", pos: "adjective", def: "silent but visibly angry", note: "Invented." },
  { w: "wemblish", pos: "adjective", def: "unsteady on the feet", note: "Invented — although <em>wamble</em>, to move unsteadily, is real." },
  { w: "hushpine", pos: "noun", def: "a sudden lull in conversation around a table", note: "Invented. The nearest real thing is the folk phrase 'an angel passing over'." },
  { w: "glaverwing", pos: "noun", def: "a moth that flies only at first light", note: "Invented — no such moth, no such word." },
  { w: "torpiculous", pos: "adjective", def: "sluggish and heavy after a large meal", note: "Invented. <em>Postprandial torpor</em> is the real (two-word) answer." },
  { w: "varnicle", pos: "noun", def: "the dimple in the base of a wine bottle", note: "Invented. That dimple is the <em>punt</em>." },
  { w: "veritude", pos: "noun", def: "the quality of sounding true without being true", note: "Invented — which is either ironic or fitting. <em>Verisimilitude</em> is the real one." },
  { w: "pluviscent", pos: "adjective", def: "smelling of rain that has not yet fallen", note: "Invented. The smell after rain does have a name though — <em>petrichor</em>." },
  { w: "tenebrile", pos: "adjective", def: "visible only in dim light", note: "Invented. <em>Tenebrous</em>, meaning dark or shadowy, is real." },
  { w: "fenestrine", pos: "adjective", def: "of light cast through a window", note: "Invented, from the real Latin <em>fenestra</em>, window." },
  { w: "verdurine", pos: "adjective", def: "of the green light beneath summer leaves", note: "Invented. <em>Verdure</em>, lush greenery, is real." },
  { w: "glinth", pos: "noun", def: "the sliver of light beneath a closed door", note: "Invented — no such word, and no such name for it." },
  { w: "flisken", pos: "noun", def: "the small gust of air let in by an opening door", note: "Invented." },
  { w: "wrindle", pos: "verb", def: "to crease cloth by gripping it", note: "Invented, from 'wrinkle' by way of nowhere." },
  { w: "tarnicle", pos: "noun", def: "the metal loop on a dog's collar", note: "Invented. That loop is just a D-ring." },
  { w: "brindlewick", pos: "noun", def: "the frayed end of a rope", note: "Invented. Sailors would say the rope has <em>fagged out</em>." },
  { w: "clabberwort", pos: "noun", def: "a weed that grows only on freshly turned soil", note: "Invented, though it sounds like something in a herbal." },
  { w: "mundicle", pos: "noun", def: "a small everyday object that has no name of its own", note: "Invented — and self-defeating, since it would then have one." },
  { w: "sobrement", pos: "noun", def: "the quiet that follows laughter", note: "Invented." },
  { w: "quillimet", pos: "noun", def: "the notch cut into the nib of a quill pen", note: "Invented. That cut is simply the <em>slit</em>." },
  { w: "hesperand", pos: "noun", def: "the last bird heard singing at dusk", note: "Invented, from Hesperus, the evening star." },
  { w: "morrowsome", pos: "adjective", def: "of a problem that looks smaller in the morning", note: "Invented." },
  { w: "gallimander", pos: "verb", def: "to wander off the point while telling a story", note: "Invented. <em>Maunder</em> already means roughly this, and is real." },
  { w: "crandle", pos: "verb", def: "to walk carefully over loose stones", note: "Invented." },
  { w: "rimswale", pos: "noun", def: "the ring a wet glass leaves on wood", note: "Invented. There is no accepted word for it, which is a shame." },
  { w: "drindle", pos: "verb", def: "to run slowly down a surface, of a liquid", note: "Invented — you are thinking of <em>trickle</em> or <em>dribble</em>." },
  { w: "blenkish", pos: "adjective", def: "pale from want of sleep", note: "Invented." },
  { w: "gorminate", pos: "verb", def: "to stare into the middle distance while thinking", note: "Invented — though <em>gormless</em>, its apparent relative, is real." },
  { w: "quaverling", pos: "noun", def: "a voice made unsteady by cold rather than nerves", note: "Invented." },
  { w: "snorrick", pos: "noun", def: "a knot pulled too tight to undo", note: "Invented." },
  { w: "umberwash", pos: "noun", def: "the brown light of a dust storm", note: "Invented, from the pigment umber." },
  { w: "murgle", pos: "verb", def: "to laugh with the mouth closed", note: "Invented." },
  { w: "glomber", pos: "verb", def: "to climb awkwardly, on hands and knees", note: "Invented — <em>clamber</em> is the real one." },
  { w: "plensive", pos: "adjective", def: "quietly regretful", note: "Invented. <em>Pensive</em> is real and close enough to fool most people." },
  { w: "cindrous", pos: "adjective", def: "resembling cold ash", note: "Invented. <em>Cinereous</em>, ash-grey, is real." },
  { w: "lumenette", pos: "noun", def: "the small light left burning for a child", note: "Invented. It is a night light." },
  { w: "gravelock", pos: "noun", def: "the sound of gravel underfoot", note: "Invented." },
  { w: "sallowick", pos: "noun", def: "the pale band of skin left by a removed ring", note: "Invented." },
  { w: "windleset", pos: "noun", def: "the pattern wind leaves on dry sand", note: "Invented. Geologists call those <em>ripple marks</em>." },
  { w: "yarnicle", pos: "noun", def: "a small tangle in a ball of wool", note: "Invented." },
  { w: "dawnling", pos: "noun", def: "the first bird call before sunrise", note: "Invented — the whole performance is the <em>dawn chorus</em>, which is real." },
  { w: "mirthling", pos: "noun", def: "a laugh that escapes at the wrong moment", note: "Invented." },
  { w: "scrimble", pos: "verb", def: "to write hurriedly and illegibly", note: "Invented. <em>Scribble</em> got there first." },
  { w: "felloquy", pos: "noun", def: "a conversation between two people who dislike each other", note: "Invented. <em>Colloquy</em>, a formal conversation, is real." },
  { w: "duskerly", pos: "adverb", def: "in the manner of failing light", note: "Invented." },
  { w: "glimmerwick", pos: "noun", def: "the last inch of a burning candle", note: "Invented. The stub is a <em>candle end</em>, unglamorously." },
  { w: "hushet", pos: "noun", def: "the small silence between two sounds", note: "Invented." },
  { w: "sundrift", pos: "noun", def: "a patch of sunlight that moves across a floor", note: "Invented." },
  { w: "tacitude", pos: "noun", def: "the habit of saying very little", note: "Invented. <em>Taciturnity</em> is the real word, and cats have it." },
  { w: "wintermark", pos: "noun", def: "the ring in a tree left by a hard winter", note: "Invented. Those are simply growth rings, read by <em>dendrochronology</em>." },
  { w: "zephyrine", pos: "adjective", def: "of a breeze too slight to move a leaf", note: "Invented. <em>Zephyr</em>, a gentle west wind, is real." },
  { w: "cloudle", pos: "verb", def: "to gather slowly, the way cloud does", note: "Invented." },
  { w: "frostling", pos: "noun", def: "the first frost of the year", note: "Invented." },
  { w: "lanterling", pos: "noun", def: "a moth circling a lamp", note: "Invented." },
  { w: "bellhollow", pos: "noun", def: "the pause after a bell stops ringing", note: "Invented." },
  { w: "rainwick", pos: "noun", def: "the drip from an eave after the rain has stopped", note: "Invented." },
  { w: "shimwrack", pos: "noun", def: "the heat haze that hangs above a road", note: "Invented. That shimmer is a <em>mirage</em>." },
  { w: "petrilune", pos: "noun", def: "the moon seen through mist", note: "Invented." },
  { w: "lattermorn", pos: "noun", def: "the hour of the morning after the rush is over", note: "Invented." },
  { w: "sundle", pos: "verb", def: "to divide something into unequal parts", note: "Invented." },
  { w: "gleamsome", pos: "adjective", def: "catching the light in a way that draws the eye", note: "Invented." }
];
